cms-sw/cms-bot

process-pull-request
- Allow L2, releasesManager to trigger tests.
- Allow more complex sentences when asking for tests.
=> Improved starting of the tests.

release-deploy-afs
The script is stuck trying to grep for 2000000 but now the quota is 3000000.
https://cmssdt.cern.ch/jenkins/job/release-deploy-afs/331/console
=> Grep for 2000000 or 3000000 in volume quota

process-pull-request
=> Revert "Flag "tests-started" when starting tests for a PR."

auto-update-git-branches
That is:
7_1_X to 7_2_X
7_2_X to 7_3_X
7_3_X to 7_4_X
=> Disable forward port of CMSDIST branches to 72X, 73X, 74X.

categories.py
Pull request cms-sw/cmssw#7305 adds a package for a new Phase2 tracker cluster.  As suggested in the comments on that pull request the package should be categorised under reconstruction.
Note that this package is only available in the CMSSW_6_2_X_SLHC branch.
=> Add DataFormats/Phase2TrackerCluster to reco

build-cmssw-ib-with-patch
Update the logic so that we have tags for releases with ERRors. Those tags will be used when generating IB summary pages.
=> Tag full releases with errors with ERR tag

get-pr-branch
When it doesn't find a branch for a pull request it doesn't fail, so it is more difficult to tell if there is something wrong in the other scripts that use this one.
=> Fail when a pull request is not found

build-cmssw-ib-with-patch, build-release
first build, upload and deprecate-local the *-tool-conf and then build release; use --tag option to avoid conflict b/w two build of same arch
=> deprecate-local and --tag options for release build

build-cmssw-ib-with-patch
This should alleviate the need of downloading externals every time we build, by reusing a previously setup area, if available.
=> Make builds reuse previous areas.

build-cmssw-ib-with-patch
- make sure we delete the previously generated SPECs
- fast-forward the cmsdist/pkgtools braches to origin
=> fixes for build area reuse

process-build-release-request, report-build-release-status
If someone wrote "+1" before tool-conf finished. The trigger of the builds was not working properly.
=> AutoBuilds: Fix the handling of pending build archs after tool-conf

process-build-release-request, report-build-release-status
I regorganized the script to comply with this diagram:
https://docs.google.com/drawings/d/1H7Xsa-KXnsX6ZSQrskKrJjLbGPteAMHYuyMeAF2vjC8/edit?usp=sharing
This organizes better the process and defines which actions are
possible during each step.
I also added the generation of an annoncement template, and the
automatic trigger of the clean up 2 days after the build
was aborted or the release was announced.
=> Automatic Builds: Organize and add mising states.

scram-package-monitor
1) Surround start/stop file touching in try/catch.
2) Check the time limits by comparing the most recent timestamp file and the oldest instead of the WORKDIR
Tested locally building Validation/* no issues observed.
=> Two fixes for scram-package-monitor.

scram-package-monitor
Another small fix to avoid a possible exception thrown when WORK_DIR has been moved by a concurrent process.
Tested locally.
=> Fix possible exception thrown when listing a non existing directory.

build-cmssw-ib-with-patch
Before, if the repository directory existed but it was empty it didn't clone it again. Now it should also check if it is empty.
=> IB builds: Check also if repository is empty

process-build-release-request, report-build-release-status
- The previous release name can still be scpecified in the
comment as it was before.
- The previous release name is obtained by decreasing the last
number of the release name by 1. If it is a patch or a
pre-release and the number is 1, the last part of the name is
removed. For example, for CMSSW_6_2_0_SLHC25_patch1 the
previous release would be CMSSW_6_2_0_SLHC25. If it is a
production release and the number is 0, the previous release
would be the name + 'pre9'. For example, for CMSSW_7_1_0, the
previous release would be CMSSW_7_1_0_pre9
- The announcement email can be generated by clicking on the
link, but the template was left in the comment to allow it to
be used if the email client or the brower are not configured.
(Resolves cms-sw/cmssw#8652)
=> Guess the previous release name and add a link to announce the release:

process-build-release-request, release-deploy-afs, report-build-release-status
For each architecture, now after the upload-ok label, a installation-ok label will be assigned when the AFS installation job succeeds. This will make sure that when the announcement is generated, the AFS installation job ran successfully in Jenkins. 
Also, after generating the release notes for the first time, now they can be generated using the "release notes" comment again if needed.
=> Report installation result and allow to generate the release notes more than once. 

tag-and-schedule-ibs
As you can see in the IB Pages for [CMSSW_7_5_ROOT5_X](https://cmssdt.cern.ch/SDT/html/showIB.html#CMSSW_7_5_ROOT5_X), some of the IBs look like there were many pull requests included and these pull requests were already merged some time ago. This has also affected 7_5_X. For example, for [CMSSW_7_5_ROOT5_X_2015-05-04-2300](https://cmssdt.cern.ch/SDT/html/showIB.html#CMSSW_7_5_ROOT5_X_2015-05-04-2300) you can see that https://github.com/cms-sw/cmssw/pull/8502 and https://github.com/cms-sw/cmssw/pull/8487 "were included" but they were merged more than a month ago. The pages also show many merges commits from the automatic forward ports. 
I did the following command on the CMSSW_7_5_ROOT5_X branch:
<pre>git log --graph --merges --pretty="%h,%s,%cd,%d"</pre>
And I noticed that the tags are …
=> Avoid tagging on commits brought by automatic forward ports.

comparisons/validate.C
This PR moves the legend off the plot area for the validateJR produced plots.
A sample output is given below.
@cvuosalo
=> Moving plot legend for validateJR plots

comparisons/validate.C
This is an update to the readability of the plot outputs from validate.C. 
In addition, it adds some statistics to the plot.
An example of the output can be see below.
=> Update validate.C readability

logRootQA.py, run-pr-comparisons
@smuzaffar @degano - could you update the cms-bot used to run pr tests to include this PR (and my last one) - it will just add a log file for the moment (which after some testing we could add to the cmsbuild report when comparisons are done.
=> add my logroot qa to run-pr-comparisons

githublabels.py, process_pr.py
hold is now again a global state
- L1/any L2 and release manager can ask to put the PR on hold
- Each user who has put the PR on hold has to explicitly request for unhold
- L1 can unhold it for all
=> hold is again a globla state

build-cmssw-ib-with-patch, build-release
After running several CMSSW compilation tests on ppc64le and x86_64 with
X and 2 * X threads (-j), where X is number of available virtual cores, I
have not detected any significant difference in elapsed time.
This is expected due to the nature of our heavy translation units and
a long debug information optimization step.
Thus moving to X + 1 should make sure we are not swapping while
compiling CMSSW while still maintaining same elapsed time.
Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>
=> Do not use twice more threads than available virtual cores

cvmfsInstall.sh
aarch64 and ppc64le should use QEMU/PRoot + custom rootfs setup for
installing releases.
Signed-off-by: David Abdurachmanov <david.abdurachmanov@gmail.com>
=> [RFC] cvmfsInstall.sh: add PRoot/QEMU environment support

categories.py
functions used in PatUtils are actively used in miniAOD and related sequence definitions. Reco L2 is responsible for miniAOD maintenance.
=> add PhysicsTools/PatUtils to reco

watchers.yaml
I am adding my user as watcher for EGM-related packages to make it easier to follow the modifications in the code. I am adding my user as watcher for the following packages:
+- EgammaAnalysis
+- RecoEcal
+- RecoEgamma
+- RecoParticleFlow
+- DataFormats/ParticleFlowReco
+- DataFormats/ParticleFlowCandidate
+- DataFormats/EgammaCandidate
+- DataFormats/EgammaReco
I also add some PF packages, since I am interested to follow their modification and possible interplay with EG PF. Let me know if this is not acceptable.
Best.
=> Add Rafael as watcher for EGM-related packages

run_class_dumper.sh
-disable-check option apparently turns off the cms checkers.
=> Remove -disable-check options from checker options

categories.py
I didn't realize that there were two packages needed by cms-sw/cmssw#14885. This is the second one.
=> add RecoLocalTracker/Phase2ITPixelClusterizer package to category

comparisons/makeDiff.sh
this should fix issues with recent issues in jenkins comparison jobs
=> makeDiff.sh to return exit 0 after root .qqqqqq

watchers.yaml
Request to watch L1Trigger related projects.
Edited `watchers.yaml` instead of `category-watchers.yaml` since the latter is too inclusive.
=> adding L1T on kreczko watchlist

DMWM/latest-dmwm-versions.sh
This adapts to the restructuring of directories that happened coincident with the adoption of cmspkg.
=> Use the latest set of RPMs

logRootQA.py
not sure why I dont see this locally - likely a sign of another problem
=> protect against vars not getting defined by os.walk - 

comparisons/validate.C
this removes empty png files from failed attempts to plot packedCands
=> in comparisons: delete unused canvas for aborted plotvar

comparisons/validate.C
I wasn't able to get these both plot (not throw) and show different results in local environment.
To be fixed later, maybe.
This is hopefully the last PR on the subject of the packed cands set of plots.
=> reco comparisons: remove packed vx,y,z plots (found to be non-reproducible in jenkins)

docker_launcher.sh
Unit test was failing for build on slc7 (which runs on docker container), listed here, complaining about environmental variable. 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_aarch64_gcc700/CMSSW_9_2_X_2017-05-21-1100/unitTestLogs/Alignment/MillePedeAlignmentAlgorithm
=> Fixing missing env var for slc7

watchers.yaml
Add DryRun to watchers.yaml for DQM/HcalTasks and DQM/HcalCommon.
=> Add DryRun to watchers.yaml

categories.py
Adding current DQM conveners Kaori Maeshima and Virginia Azzolini as L2 for DQM
dmitrijus remains as main responsible for reviewing and signing PRs
vanbesien will/should be removed end of September
=> Adding Kaori and Virginia as L2 for DQM

comparisons/validate.C
updates match recent developments in corresponding products.
There is no other validation (no DQM) so far for OOT photons and isolatedTracks.
=> update in reco comparisons: OOT photons, HI vertices, update isolatedTracks

comparisons/matrix_RE.txt, comparisons/validate.C
Since a few days we have more complete set of 2017B workflows. The map update is also to align with the proposed https://github.com/cms-sw/cmssw/pull/19944 which would add a single photon workflow 136.788 to the short matrix tested by jenkins
validateJR fwlite plots were updated to include currently standard ID flags in the BeamHaloSummary
=> reco comparisons updates: 2017 data workflow map and monitor beamHalo flags

run-pr-comparisons
plots in SiStrip/MechanicalView have been failing for over a year now in data workflows in a mode that generates O(10K) plots with differences which take forever to print to file (even worse considering that jenkins does it for pdf and ps).
something similar could probably be done in relmon plots as well, but I'm not aware of an anti-pattern option there.
This PR should reduce the CPU wasted by at least a factor of 2 (I'm guessing that relmon takes about the same time to make these plots).
=> skip SiStrip/MechanicalView plots in alternative-comparisons

run-pr-comparisons
date timestamps are added to aid occasional tracking or debugging of the comparisons jobs
=> add timestamps to progress messages in run-pr-comparisons

run-pr-comparisons
Reverts cms-sw/cms-bot#881
after https://github.com/cms-sw/cmssw/pull/20050 is merged in CMSSW_9_3_X_2017-08-04-1100
it looks like SiStrip/MechanicalView monitoring in CMSSW is now apparently stable and does not go on/off randomly producing empty plots.
this damage control fix from #881 is not  needed anymore
the processing times are also consistently low https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/buildTimeTrend
I checked several cases that took more than 1h, and in all of them apparently there are 30 mins spent in moving the outputs out (most likely all in send_jenkins_artifacts calls)
=> Revert "skip SiStrip/MechanicalView plots in alternative-comparisons"

comparisons/validate.C
- bug fix: use try/catch in all packedCandidates plots
- previously plots of data members directly could complete; now it looks like ROOT is calling constructors still and the plots fail. This update fixes the problem by catching the exception
- Here is an example log from jenkins: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_3_X_2017-08-20-1100+19964/22029/validateJR/all_mini_OldVSNew_RunSinglePh2017B136p788/all_mini_OldVSNew_RunSinglePh2017B136p788.log
- new plots: add plots of reducedGsfTracks for the new product added in https://github.com/cms-sw/cmssw/pull/19964
=> reco comparisons updates: reduced GSF; use try/catch in all packedCandidates plots to let plots complete

comparisons/validate.C
add plots for 
- muon selectors bits [recent addition in the reco::Muon data formats]
- offlineSlimmedPrimaryVertices [old product; correct omission in validation]
=> comparisons validateJR: add plots for muon selectors bits and for offlineSlimmedPrimaryVertices

lizard-processing/src/lizard_to_html.py
Updated lizard_to_html.py script so that it would sort on CNN column by default.
=> Lizard, sort by CNN in descending order.

categories.py
New package proposed in https://github.com/cms-sw/cmssw/pull/21298 .
The reasoning behind putting it under alca (in `CalibTracker/`) was that most of the packages that use it are there (but now there are also some in db (CondCore/SiStripPlugins), and in visualization, so maybe geometry would be more appropriate?)
=> Add CalibTracker/StandaloneTrackerTopology to categories.py

run-pr-code-checks
the URL in the "HOW-TO" and ```Logs: ``` part of the message was already correct, but the link URL was still the old one.
This should fix the difference.
=> fix link URL for code-checks message

categories_map.py
Package HeterogeneousCore/CUDAServices has been proposed as the first one of a list for a new Subsystem. Assigned to the Core category.
@Dr15Jones @smuzaffar please suggest an alternative if you consider it more appropriate
=> Add package HeterogeneousCore/CUDAServices to the Core category

comparisons/matrix_RE.txt, comparisons/validate.C
- refactor tau plot parts for patTaus
- add plots for tauIDs and other "user" variables
- add HI2018 MC 150.0 , nanoAOD MC 1325.7, and 2016H reminiAOD 136.7721 wfs  to the map (this will also silence the warning message showing up in every PR about a missing map for the nanoAOD wf. ... I left it there for some time hoping for a faster implementation of some basic nanoAOD monitoring in validate.C)
=> reco comparisons updates: tau ID plots; recent wfs in the map

categories.py, categories_map.py
As agreed, a new empty category "xpog" with no CMSSW package associated is added, and the present XPOG coordinators are associated as responsible. This addition is intended to support the forthcoming AN release branch management, where the integration will be mostly done based on agreement from the XPOG coordinators (+ basic technical tests).
=> Add category xpog with no package associated for AN release branch management

categories.py, categories_map.py
For the management of the AN release: use the standard analysis category, remove the xpog category with no package assigned.
=> Add XPOG coordinators to the analysis category, remove the xpog category with no package assigned

comparisons/matrix_RE.txt, comparisons/validate.C
- map file is updated to cover recent additions/changes in (re)miniAOD workflows
- fwlite-based scripts updates:
- pat::MET plots now include PAT-specific variables including uncertainties
- plots for ```particleFlowRecHitECAL__ ``` were added for debug purposes (this collection is not saved by default in RECO or higher data tiers checked in jenkins)
=> reco comparisons: map updated for miniAOD workflows; plots for pat::MET

comparisons/matrix_RE.txt, comparisons/validate.C
- map updates
- 10811 added
- this should have no effect on jenkins tests]
- fix 1325.7 wildcard to match to the latest update
- used in jenkins and triggers warnings now
- make MC wildcards more inclusive to handle MC with external inputs ("INPUT" text may be added when that input is available)
- this is relevant only for private tests now
- fwlite plots updates
- add plots for pat::Muons for recently added variables
- this will show up in jenkins tests
- step specifications now have an underscore enforced as a separator so that the map short name or other parts do not accidentally match the step specifications (in most cases we run "all_", but other options are present and are used occasionally)
- this should have no effect on jenkins tests
- add plots for PF debugging (pfdebug_ step …
=> comparisons:  map updates; reco comparisons/validate.C add recent muon variables, PF debug plots, more strict configuration

logRootQA.py
This PR revises the logic behind the `DQMHistoSizes` comparison output. It slightly changes its paradigm: from a tool to estimate run-time memory use (which was always flawed, but useful in the past), to one that automates a big part of DQM PR validation: check that the code changes only affect the DQM output that they claim to affect.
In more detail
- it now looks at harvesting output, and covers the full DQM process.
- it uses the "baseline camparison" feature of `dqmMemoryStats.py` to get a detailed difference in content.
- it condenses down this comparison to no more than 11 lines, deduplicating changes in multiple files and truncating the rest. These lines are added to the `SUMMARY`.
- it reports workflow numbers for the changes found, to give a hint where to start debugging when …
=> DQMHistoSizes: make output more detailed

logRootQA.py
The regular expression for the total change does not capture the sign, so it will always detect a size increase... the detailed statistics however are fine.
This fixes the regular expression.
(spotted in #979, though but not related to it)
=> Fix sign in DQMHistoSizes

comparisons/analyzeFWComparison.py
this should resolve the #985 
before:
```
Processing: all_OldVSNew_TTbar13TeVPUppmx2018wf250202p181
Workflow number is: .
```
after:
```
Processing all_OldVSNew_TTbar13TeVPUppmx2018wf250202p181
Workflow number is: 250202.181
```
=> more specific WF_REGEXP in analyzeFWComparison.py

comparisons/matrix_RE.txt, comparisons/validate.C
the map file update will address the warnings that now appear in the jenkins tests
=> reco comparisons updates:  Run2018A map entries; add log pt plots for packed candidates

openstack/hg/os.sh
@smuzaffar the openstack-create job is failing again, and it turns out the previous image is no longer available. 
This script should be able to discover what's the image name available (assuming only one CC7/SLC6 match)
=> Auto-discover CC7 and SLC6 images available for DMWM

categories.py
Hello @smuzaffar @fabiocos  , Tongguang is starting as AlCa/DB convener and thats why we would like to add him as L2 in github holding AlCa signature.
Could you please consider this request. 
Thanks.
FYI @tocheng @lpernie
=> adding Tongguang Cheng as L2 AlCa

watchers.yaml
as SiStrip local reco, calibration and alignment L3 convener, to follow strip tracker-related PRs
=> Update watchers.yml for pieterdavid

comparisons/matrix_RE.txt, comparisons/validate.C
- first version of nanoAOD comparisons is added to validate.C.
-  This comparison is added with an assumption that the nanoaod::FlatTable muonTable data is present only in nanoAOD file. If the corresponding branch is present in the input file, only nanoaod::FlatTable will be made and the rest of the comparisons will be skipped.
- I think that this is safe for now, but may need a fix if/when we have workflows running both RECO or PAT steps together with the NANO step
- The overhead of checking all other possible branches is too large and I wanted to minimize the time it takes to process the input nanoAOD files.
- map files were updated with entries corresponding to the  available nanoAOD outputs
In the current jenkins tests I expect the new comparisons to show up for workflows 1325.7 and …
=>  nanoAOD EDM file monitoring added to the reco comparisons validate.C #149 

comparisons/matrix_RE.txt, comparisons/validate.C
- map file updated to include
- the HI repacking emulation workflow 140.55
- the highBetaStar 2018 workflows from the commissioning2018 data
- validate.C updates
- switch to ```detId().subdetId()``` in calo rechit plots to avoid massive memory leaks via TCling
- add reco::Track t0 and beta plots (part of MTD integration)
- add RP timing detector plots for digis and rechits and update other PPS rechit plots
=> reco comparisons: avoid mem leaks; add track time and PPS timing plotsComparisons 4 oct2018

comparisons/matrix_RE.txt
- update cosmics wf 2018 to get rid of the warning about a missing map for wf 7.3 now appearing since CMSSW_10_4_X_2018-11-07-2300
- add new production-like HI workflows for tests
=> reco comparisons map update 

run-pr-comparisons
Followup changes for #1009 to make a list of reco comparisons with differences, in addition to failed DQM comparisons.
I tested the bash code standalone on a few logs, and it seems to work fine.
=> Add reco comparison differences to validateJR.html

comparisons/validate.C
- MTD track extension variables, track tofPID, and new vertex collections
- additional/new PPS local track variables
- some refactoring of copy-pasted values or calls
- add branch presence check for most of the complex types with more than 1-2 plotted members to cleanup the logs
- e.g. all_mini comparisons logs reduced by more than a factor of 4 from 1.9 MB to 0.4MB (for a case of no differences)
=> reco comparisons: new PPS and MTD plots; add branch presence check for cleaner logs

comparisons/validate.C
Updates in reco comparisons for the following areas:
- PPS: fix method name in ctppsLocalTrackLiteProducer
- EGM/bParking: plots similar to regular electrons and conversions
- Muons: plots for crossedHadRecHits
=> reco comparisons: plots for new products/variables including bParking/lowPt electrons

categories_map.py
cms-sw/cmssw#26187 moves FastSimulation/BaseParticlePropagator to CommonTools/BaseParticlePropagator . This affects both reconstruction and fastsim, the new utility package may be jointly supervised by both categories
=> In support of cmssw#26187, add CommonTools/BaseParticlePropagator to fastsim and reconstruction

run-pr-comparisons
Since the tool was moved from bot to CMSSW, we have to invoke differently. Added additional conditional to check if tool exists so this PR could be merged immediately.
=> A fix to pick the correct version of DQM bin by bin comparison tool.

run-pr-tests
Addressing https://github.com/cms-sw/cms-bot/issues/1111
=> Add TimeMemorySummary.py as default option for every runTheMatrix.py workflow

comparisons/matrix_RE.txt, comparisons/validate.C
New plots:
- electron HEEP iso and conv prob;  photon charged hadron iso and shape 2nd moment
- muon: low-pt MVA
- packed candidates: associated depth value map; caloFraction
- prefiringweight for L1 (non)prefire probability
- another rho variable
Map updates:
- RunEGamma2018C for private tests
- 11624 is now from 2021 (renamed from 2019)
- this should get rid of the warnings recently appearing in the comparisons run by cms-bot/jenkins
=> reco comparisons updates: new plots and updated workflow map

categories_map.py
We only have cms-data/RecoTauTag-TrainingFiles repository which should be under reconstruction.
=> Added  RecoTauTag/TrainingFiles under reconstruction

run-pr-comparisons
This PR fixes an issue where multiple PRs separated by a space inside PULL_REQUESTS argument causes the tool to misbehave.
=> Escape an argument to support space separated values in DQM bin by bin tool

categories.py
Ben Krikler is our new L1T DQM convener.  He is replacing Thomas Reis. 
He will mostly be taking care of L1 PRs that have to do with DQM oriented software, but hopefully will also assist with the main L1 PRs.
Please approve.  Thanks.
=> Add new L1 sign-off responsible - Ben Krikler.

create-new-data-pr.py
Add script for releasing and tagging on cms-data pr merge.
It also creates cmsdist pr with the new tag on the default cmsdist branch
=> cms-data release creation script

categories_map.py
Update of https://github.com/cms-sw/cms-bot/blob/master/categories_map.py to add the new package FWCore/Refelction proposed in cms-sw/cmssw#27287 . The package is assigned to the "core" group.
=> Add FWCore/Reflection in support of cms-sw/cmssw#27287

run-ib-comparison-baseline
The simple performance monitoring already added to PR tests in #1142 is now added also to the IB comparisons baseline, writing its output only into JobReport .
=> Run performance monitoring for comparison baseline 

es/templates/cmssdt-runthematrix-data.json, es_relval_log.py
Update 
https://es-cmssdt.cern.ch/kibana/app/elasticsearch_status#/index/cmssdt-ib-matrix-2583?_g=()
index with more fields and put the fields on elasticsearch (for plotting them, assuming)
Example for the new fields types taken from here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_0_X_2019-07-01-2300/slc7_amd64_gcc700/-GenuineIntel/matrix-results/250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/JobReport2.xml
=> Update templat and remove write filter condition for ib-matrix index

comparisons/matrix_RE.txt
This should clear the warnings appearing in comparisons since CMSSW_11_0_X_2019-07-17-2300.
wfs with the same numbers had 2023D\* in the names in the range [CMSSW_11_0_X_2019-07-10-2300, CMSSW_11_0_X_2019-07-17-2300). It seems OK to ignore this range of IBs and support just longer-lived name patterns for wfs ==> I'm renaming the existing entries instead of extending the map.
=> reco comparisons: rename 2023 to 2026 for phase-2 workflows in 110X

categories_map.py
I noticed in https://github.com/cms-sw/cmssw/pull/27613 that this package was missing from the simulation category. It seems to me that it belongs there (in addition to core, where it is currently assigned).
@civanch FYI
=> add BigProducts/Simulation to simulation category

rucio/setup.sh
Implemented minimal changes, tested locally with both bash and zsh from different directories, providing both absolute and relative paths. `$BASH_SOURCE` is obviously only defined for bash.
=> Make rucio setup.sh zsh compatible

pr_testing/test_multiple_prs.sh
We create cmssw dev area while PR testing. This means during PR tests we have following paths in LD_LIBRARY_PATH
- `CMSSW_BASE/biglib/SCRAM_ARCH`
- `CMSSW_BASE/lib/SCRAM_ARCH`
- `CMSSW_BASE/external/SCRAM_ARCH/lib`
- `RELEASETOP/biglib/SCRAM_ARCH`
- `RELEASETOP/lib/SCRAM_ARCH`
- **`RELEASETOP/external/SCRAM_ARCH/lib`**
Now if newer version of an external has removed a library and we did not update the tool's toolfile then during PR tests the missing library is still found via `RELEASETOP/external/SCRAM_ARCH/lib` and PR tests run successfully. 
This PR makes sure that during PR tests we remove `RELEASETOP/external/SCRAM_ARCH/lib` and all external libs should be available via `CMSSW_BASE/external/SCRAM_ARCH/lib`
=> remove cmssw/externals/arch/lib for PR testing

comparisons/matrix_RE.txt
- fix mappring for workflow 135.4 [bugfix]
- minimal map for recent/new 2026 workflows: D43, D45, D4[7-9]: [supersedes #1229 ]
=> reco comparisons: workflow map updates

releases.map
=> Mark CMSSW_8_0_34_UL/slc7_amd64_gcc530 as production release

es_externals_stats.py, es_utils.py
This adds changes for
1.    Add summary function get_summary_stats_from_dictionary
Records are as expected
https://es-cmssdt.cern.ch/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:AW_svgachldp7JMpTV51,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))
2.    Add script to be used by Jenkins
The result of es_send_resource_stats was validated against result produced with the old version,
jsons (values of sdata, see line 248) are the same
=> Exernals stats on Elastic (rebased)

groups.yaml
Removing people no longer associated with CMS from the list of BTV POG package watchers. The request came from @HeinerTholen but I took the occasion for some additional cleanup (@acaudron, @pvmulder).
@JyothsnaKomaragiri and @smoortga, let me know in case you would like to be removed.
Also keeping in the loop @mverzett, @emilbols, @andrzejnovak
=> Cleanup of BTV POG package watchers

pr_testing/test_multiple_prs.sh
Check for build errors during static checks. This might identify build errors due to the use of EDM_ML_DEBUG.
For Development release cycle: In case of build errors, this should add a new link on PR summary page which should point to static analysis build long.
=> check for static check logs for build errors

comparisons/validate.C
updates in validate.C used for reco comparisons. The main part is the addition of monitoring for TICL reconstruction, which is available in the default workflows since 11_1_0_pre6.
=> reco comparisons: TICL monitoring: tracksters with multiclusters, TICL and PF Candidates

run-pr-code-checks
If clang-tidy itself fails then code-checks ignore all fixes and continue. This was observed for https://github.com/cms-sw/cmssw/pull/29527 where PR itself does not compile as it depent on another PR. This change will allow to mark code check fail if clang-tidy fails
=> Code check fix

run_clang_static_analysis, statics-filter1.txt
The only way to avoid reporting the link to statics in ```edm::ConcurrentHadronizerFilter<Pythia8Hadronizer, gen::ConcurrentExternalDecayDriver>::filter()```  is to mark all statics linked through the base class as safe. To avoid doing this just filter edm::ConcurrentHadronizerFilter<Pythia8Hadronize  from the modules2statics report.
=> Filter 'edm::ConcurrentHadronizerFilter<Pythia8Hadronizer' in modules2statics report

comparisons/filter-failed-comparison.py
During the PR tests of https://github.com/cms-sw/cmssw/pull/30071 we noticed that we are filtering  too many file files due to directory separator `_` and character `_` in the name. This PR make sure that we process all files and only filter out those which are clean
=> drop only those files which are all clean

comparisons/validate.C
- move caloTowers plotting to a separate method 
- add a plot for PFTowers (present in heavyIons workflows only); triggered by changes in cms-sw/cmssw#29948 
- bugifx mass2 method name, should be massSqr (since ever)
no changes are expected in the reco comparisons summaries
=> reco comparisons: update in caloTowers

comparisons/validate.C
- MTD
- fix time error variable accessor name (```timeError```) for FTLClusters
- drop nonexistent value (transient) plotting of positions in mtdTrackingRecHits
- add plots of BTL and ETL chi2 matches with tracks
- NANO
- update the list of plotted tables to the full list available as of CMSSW_11_2_X_2020-06-18-1100
the comparisons on jenkins tests are expected to run and return no differences on "self"-comparisons
=> reco comparisons: nanoAOD and MTD plot updates

comparisons/matrix_RE.txt, comparisons/validate.C
-  add HI 2018 reminiAOD workflow mapping, in support of cms-sw/cmssw#30354
- also, drop a plot of nonexistent variable in MTD tofPID
=> reco comparisons:  add HI 2018 reminiAOD workflow mapping

comparisons/validate.C
- add plots for JPT jets AK4 (forgotten post-migration from AK5 since a while). Needed for cms-sw/cmssw#30430
- add plots of counts of packedCand refs from packedCandidateMuonID (heavy ions re-miniAOD). Needed for/after cms-sw/cmssw#30253 
- hiPixelTracks as packed candidates (heavy ions re-miniAOD). Needed for/after cms-sw/cmssw#30313
=> reco comparisons: plots for JPT jets;  packed candidates from heavy ion miniAOD

docker_launcher.sh
Testing showed that commenting out the ulimit commands allowed igprof to run under Singularity. 
Used the Jenkins job parameter/ environment variable ADDITIONAL_TEST_NAME to skip running ulimit when ADDITIONAL_TEST_NAME=igprof.
=> If igprof is being run do no set ulimit.

docker_launcher.sh, run-ib-igprof
The segfault while running igprof under Singularity in docker_launcher.sh was caused by setting `ulimit -s unlimited`. Changing this to `ulimit -s 81920` results in no segfault.
=> Run igprof under Singularity with limited stack size set by ulimit -s. Updates to igprof job scripts.

comparisons/validate.C
- for slimmed/reduced muon clusters/extras from cms-sw/cmssw#31217: add some basic plots or `reco::TrackExtra` and the associated pixel/strip clusters
- comes with some refactoring of existing plotting methods for the tracker clusters
- for slimmedHcalRecHits from cms-sw/cmssw#31375 : basic plots for HBHE/HO/HF hits are added
- comes with some refactoring of existing plotting methods for the calo rec hits
- add a plot for hbhe rechits chi2 after some minimal energy cut
- add pat Electron and Muon BS2D and PV2D plots
- adjust the stats text and the exponent label offset for x and y axis plots to avoid/minimize overlapping or invisible text
=> updates in reco comparisons: plots for new products, minor style updates

comparisons/matrix_RE.txt
apparently it took more than 2 months to discover that the reco comparisons plotter is looking at a wrong process name.
=> bugfix in process name used for reminiAOD for HI MC reco comparisons mapping

run-ib-igprof
Fix another bonehead mistake in copying over awk command from profiling script were it is echo-ed into a file to be run later.
=> run-ib-igprof:  Remove escapes from $ in awk command

jenkins-artifacts, pr_testing/test_multiple_prs.sh
For profiling test results it would be useful to have Igprof and Circles available to browse. This is done with relative symbolic links in the igprof and profiling directories for the nightly IB release built against. 
ToDo: How to make links to the files?
=> For profiling add symbolic links so Igprof and Circles files can be read

categories.py
In commit f5ee9fa7b9788cef892019d7c0d2ee68eccd5cab, I copied the username from the URL https://github.com/YuanChao, not realizing that the username in the URL is not case sensitive, though the username itself apparently is (at least for the cms-bot). As a consequence, @yuanchao could not sign off on PRs, such as https://github.com/cms-sw/cmssw/pull/31586#issuecomment-702821191. 
This PR corrects the case of the username.
=> Correct case of username yuanchao

pr_testing/test_multiple_prs.sh
This should allow to upload externals for PR tests and reuse pre-build externals for last run.
Uploaded repo name will be `cms.<week>.PR-<hash>-<release-queue>-<arch>`. Once uploaded then jenkins can automatically install this under /cvmfs/cms-ci.cern.ch
=> upload cms externals for PR tests

comparisons/validate.C
- hiEvtPlane from cms-sw/cmssw#31129
- packedPFCandidatesCleaned from cms-sw/cmssw#31668
- offlineSlimmedPrimaryVerticesRecovery from cms-sw/cmssw#31676
=> reco comparisons: new plots for HI miniAOD

github_utils.py, mark_commit_status.py, pr_testing/run-das-query.py, pr_testing/test_multiple_prs.sh
This adds a new tests for Pull requests testing. Tests make use of `runTheMatrix.py --maxStep=0` option to run all das query steps. This should catch if there is any new data being access which is not yet known to DAS.
The extra test should not take more than 8-10 mins to run.
Also reset PR statuses to pending it rests are rerun.
=> added run das queries test for PRs; reset statues on rerun

run-ib-igprof
This needs to be merged before #1408 abd #1413 to generate the event size text file for PR profiling comparison.
=> Run edmEventSize on step3 and step4 root files produced by running igprof on high pileup workflow 23434.21 and save output.

categories_map.py
I can't recall this was practical or needed since the original addition in 2017 in https://github.com/cms-sw/cms-bot/commit/48f365673a6fb521c9e50439acf8c855354f6790
=> remove DataFormats/NanoAOD from the reco category

build-cmssw-ib-with-patch
=> Move WEB to DEPS before deletion and rename packages to package.json

RelValArgs.py
this runs on arm and intel
only concern is the missing wf_stats files not created by the monitor script
from 30 failing tests only 3 failed when ran without monitor indeed
=> Stop running monitor on arm

build-cmssw-ib-with-patch
old releases are having DEPS/*.json structure:
CMSSW_11_2_CLANG_X_2020-11-08-2300/slc7_amd64_gcc820/100238/DEPS/
but now they are having DEPS/arch/*.json:
CMSSW_11_2_CLANG_X_2020-11-20-2300/slc7_amd64_gcc820/100883/DEPS/
which failed the jenkins job when it couldn't copy the arch folder
when building with pkgtools having the WEB/arch structure is correct to not overwrite things,
but in this case we only build one arch within one job and renaming WEB/arch to DEPS is safe.
Everything else would require conditions in the jenkins job which is not necessary
the architecture is already in the path so having it release/arch/DEPS/arch in this case is redundant
=> Bring the old file structure for DEPS folder

comparisons/validateJR.sh
while testing https://github.com/cms-sw/cmssw/pull/32325#issuecomment-735484569
`Reco comparison had 1 failed jobs` showed up somewhat unexpectedly.
It was triggered by a request to include a workflow in the test which does not have a reference. These unpaired inputs should not be used to run validate.C (fwlite-based reco comparisons).
this PR should resolve the issue
=> reco comparisons driver: check that both input root files are available before running validate.C

categories.py
Tongguang Cheng (@tocheng) has completed his term as AlCaDB convener so I am removing him from the alca L2 list.
=> Remove tocheng from alca L2 list

run-pr-comparisons
an occasional special character in logRootQA file can break parsing of the summary of the PR tests.
One example is in https://github.com/cms-sw/cmssw/pull/32330#issuecomment-736813502
A simple test with the same file downloaded locally:
```
>grep SUMMARY logRootQA.log
Binary file logRootQA.log matches
>grep -a SUMMARY logRootQA.log
SUMMARY You potentially added 2947 lines to the logs
SUMMARY Reco comparison results: 0 differences found in the comparisons
SUMMARY DQMHistoTests: Total files compared: 28
...
```
=> treat QALOG as a text file in run-pr-comparisons

github_utils.py, pr_testing/test_multiple_prs.sh, process_pr.py, report-pull-request-results.py
An attempt to reduce pr tests messages. We make use of commit statuses to keep track of pr test states , so there is no need to post test started.
=> reduce pr test messages and make use of commit status

pr_testing/test_multiple_prs.sh, report-pull-request-results, report-pull-request-results.py
force use a wrong CMS_PATH to make sure some relvals and addon tests fail.
=> Include relval and addon failed tests links

categories_map.py
"CommonTools/TriggerUtils" contains tools used for validation of L1 and HLT objects, not really for reco.
I did not remove the ownership of analysis to the package, but perhaps this is also something that can be considered.
@cms-sw/l1-l2 @cms-sw/hlt-l2
=> Move CommonTools/TriggerUtils from reco to hlt and l1

pr_testing/run-pr-relvals.sh, pr_testing/test_multiple_prs.sh
GPU tests improvements.
Instead of building and running full separate tests for GPUs, now bot should be able to trigger a special separate test for GPU relvals.
=> run extra relval tests for GPUs

create-new-data-pr.py
following suggestion in https://github.com/cms-sw/cms-bot/pull/1466
This is tested and sorts the tags here:
https://github.com/npc-data/PhysicsTools-NanoAOD/releases
like this:
V01-07-00
V01-06-01
V01-06-00
V01-05-00
V01-04-00
V01-03-00
V01-02-06
V01-02-05
V01-02-04
V01-02-01
V01-02-00
V01-01-00
V01-00-12
V01-00-11
V01-00-10
V01-00-09
V01-00-08
V01-00-07
V01-00-06
V01-00-05
V01-00-04
V01-00-03
V01-00-02
V01-00-01
V01-00-00
although the last release/tag is 01-02-06
=> Only sort tag names

create-new-data-pr.py
This updates non default branches given they has at least one manually created tag
The suggested usage in here https://github.com/cms-data/RecoBTag-Combined/issues/41 
doesn't work because when the PR is merged the last sha of the branch changes and doesn't match the
last tag on it, and the job is always first merging the PR and then attempt to tag the branch.
Tested for
default branch
non-default with tags - in most cases the non default is branched from the default and has some tags
non-default without any tags - orphan branch with 0 tags
=>  Update tag versions on non-default branches

reco_profiling/profileRunner.py
Add a one-stop reco profiling script in `reco_profiling/profileRunner.py`.
It can be called with the following options (`--out-dir` is mandatory, the others are the defaults)
```
python3 reco_profiling/profileRunner.py --workflow 23434.21 --num-events 100 --out-dir profile_out
```
and it will create and run steps1-4, where steps 3-4 are repeated with the necessary profiling options.
The outputs are copied to `profile_out`, the script will fail if any of the steps fail and any of the outputs are missing or empty.
Comments & suggestions welcome!
cc @slava77 @gartung @smuzaffar
=> Reco profiling

run_clang_static_analysis
Older CMSSW releases do not generate eventsetuprecord-get.txt.
=> Create empty eventsetuprecord-get.txt

run-ib-igprof, schedule-additional-tests
Each job gets its own properties file. The run-ib-igprof script was also updated to split the WORKFLOWS var for use in a loop.
=> Split profiling workflows the same way for igprof and profiling jobs. 

pr_testing/test_multiple_prs.sh
Alternative way to run EventSetupRecord::get checker.
Resolves makortel/framework#69
=> Run custom CMS clang-tidy checks in PR testing.

reco_profiling/profileRunner.py
This has already been tested at https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/76/console.
We now profile both 23434.21 (100 events) and 11834.21 (400 events).
=> Update reco release profiling

pr_testing/test_multiple_prs.sh
To avoid confusion only run the cms-esrget clang-tidy check during pull request test job.
The cms-handle check offers fixit text that compiles 100% the last time it was checked for all of CMSSW and should be run as part of the code-checks job.
=> Only run the cms-esrget clang-tidy check on pull requests.

reco_profiling/igprof-fixed.sh, reco_profiling/profileRunner.py
- Calls a patched version of igprof (with 12_0_0_pre1 libigprof preloaded) for reco profiling on 11_3_0_pre5 and 11_3_0_pre6.
- Also saves JobReport.xml files for the profiles
- Tested in https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/89, https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/88 and more recent builds of https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/
- nothing in the usual bot functionality should be affected
=> reco profiling fixes

pr_testing/test_multiple_prs.sh
- reduce jenkins log size by redirecting clang and static analysis logs to log file only
=> avoid clang and static checks output in jenkins log

pr_testing/test_multiple_prs.sh
work around git-cms-addpkg issue with added '*' if there are already packages checkedout
=> Full re-build for cmssw PRs

watchers.yaml
Merging two occurrences of `tracking-pog` in `watchers.yaml`.
Was preventing me to be tagged (see https://github.com/cms-sw/cms-bot/pull/1571#issuecomment-870471591).
@VinInn, @mtosi @JanFSchulte FYI.
@vmariani, you might want to be added in here as well.
=> clean-up tracking-pog configuration in watchers.yaml

logRootQA.py
I noticed in a recent test that a size change warning is produced
but there are no details where it happens
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-20-1100+7d5caa/44238/validateJR/logRootQA.log
=> improve ROOTFileChecks size change message in logRootQA

reco_profiling/profileRunner.py
- Only changes the [reco release profiling](https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/) functionality in the bot.
- For release-run-reco-profiling, now runs igprof after everything else (step3 and step4 circles, TimeMemory etc).
- Do not abort the jenkins job in case of missing outputs.
- Motivated by the issues with igprof in 12_0_0_pre4: https://github.com/cms-sw/cmssw/pull/34517
- Tested successfully in https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/119
cc @cms-sw/reconstruction-l2
=> reco release profiling: run igprof after everything else

comparisons/validate.C
- HGC egamma collections, as introduced in cms-sw/cmssw#34439
- hcal depth values, as introduced in cms-sw/cmssw#33666
=> reco comparisons: add monitoring for hcal depth in egamma and HGC_ egamma collections

comparisons/validate.C
(these are currently present only in special HFNose workflows; one in the short matrix)
there is no coverage for these in the DQM; so this monitoring would be a good addition.
This PR is also in sync with cms-sw/cmssw#34605
=> plots for ticlTrackstersHFNose* products 

process_pr.py
This PR allows the character `'` in relvals options.
As pointed out in https://github.com/cms-sw/cmssw/pull/34599#issuecomment-890328605 this PR is not sufficient to run `--command` because of https://github.com/cms-sw/cms-bot/blob/master/pr_testing/test_multiple_prs.sh#L1002
=> Allow character ' in relvals options

categories.py, watchers.yaml
Now that we have two active upgrade L2s, I'm no longer needed as a backup L2.
I've added a few packages to my watch list to keep an eye on them (where I did a lot of the setup - upgrade workflows, geometry scripts).
attn: @cms-sw/upgrade-l2
=> remove kpedro88 as upgrade L2 

gh-teams.py
Update of the list `configdb-owners` for HLT, including new L1 (@silviodonato) and L2 (@missirol), plus removing developer who left.
FYI: @fwyzard @Martin-Grunewald @Sam-Harper
=> updated list of "configdb-owners"

report-summary-merged-prs
the first case in this json where compared_tags is "compared_tags": "CMSSW_12_1_UBSAN_X_2021-09-22-1600-->CMSSW_12_1_X", 
https://raw.githubusercontent.com/cms-sw/cms-sw.github.io/master/data/CMSSW_12_1_UBSAN_X.json
should be skipped because it resolves to searching for CMSSW_12_1_X in ubsan_logs which will never be there
the release folder to be searched in has to be always the second  element of `rel_name = c['compared_tags'].split('-->')[1]`
and in this case will search with `find` into never existing path
=> Skip search for ubsan_ib-->non_ubsan

cmssw_known_errors.py
This tries to load a shared library bundled in gridpacks (built for x86_64)
```
Matrix_Element_Handler::BuildProcesses(): Looking for processes Library_Loader::LoadLibrary(): /home/cmsbuild/jenkins_a/workspace/ib-run-relvals/CMSSW_12_1_X_2021-09-26-2300/pyRelval/573.0_sherpa_ttbar_2j_MENLOPS_13TeV_MASTER_ExtGen+sherpa_ttbar_2j_MENLOPS_13TeV_MASTER_ExtGen+HARVESTGEN/thread122997_0/Process/Amegic/lib/libProc_P2_2.so: cannot open shared object file: No such file or directory
Library_Loader::LoadLibrary(): Failed to load library 'libProc_P2_2.so'.
Library_Loader::LoadLibrary(): /home/cmsbuild/jenkins_a/workspace/ib-run-relvals/CMSSW_12_1_X_2021-09-26-2300/pyRelval/573.0_sherpa_ttbar_2j_MENLOPS_13TeV_MASTER_ExtGen+sherpa_ttbar_2j_MENLOPS_13TeV_MASTER_ExtGen+HARVESTGEN/thread122997_0/Process/Ame …
```
=> Added workflow 573.0 in to known failure for ppc64le and aarch64

comparisons/validate.C
To add supporting plots for ID variables added in cms-sw/cmssw#35403
=> reco comparisons: add DNN ID plots for electrons and photons

categories_map.py
This PR is with ref to CMSSW PR #[35965](https://github.com/cms-sw/cmssw/pull/35965) for introducing the new package - ```DQM/SiPixelPhase1Heterogeneous```
=> Add new package for monitoring pixel SoA products

pr_testing/test_multiple_prs.sh
This PR enable USE_CMS_DEPRECATED macro for PR tests ( only for master cmssw IBs). For now it will only add a new link in the summary page but PR tests will not be marked failed due to these warnings.
CMS deprecated warnings are only reported for the file which are changed in the cmssw PR
=> enable cms deprecated warnings for master's branch PR tests

watchers.yaml
As GEM-CSC trigger co-coordinator, giovanni-mocellin needs to follow the changes in some CMSSW packages
=> Added watcher giovanni-mocellin

RelValArgs.py
Trying to revert https://github.com/cms-sw/cms-bot/pull/1666 only in order to test #36297 wihìth wfs 101 and 102 in multithread
=> NOT FOR MERGING: Update RelValArgs.py

report-pull-request-results.py
Increases the maximum length of the log-file names of the `addOnTests`, as discussed in https://github.com/cms-sw/cmssw/pull/36423. More details on why this might help can be found in the latter PR.
Depends on https://github.com/cms-sw/cmssw/pull/36423.
=> increase max length of `addOnTests` log-file names

DMWM/install-wmcore.sh, DMWM/install-wmcorepy3.sh, DMWM/test-wmcore.sh, DMWM/test-wmcorepy3.sh
Starting with MariaDB 10.6.5, we no longer define a user password.
It also changes the MariaDB database name to the same defined within WMCore unittests, to avoid inconsistencies and surprises when testing things.
Further info can be found at: https://github.com/dmwm/WMCore/issues/10926
=> Access MariaDB with no password; use consistent unit test db name

comparisons/validate.C
- add plots for new MTD value maps following updates in cms-sw/cmssw#36202
- pat::Jet JEC counters in connection with cms-sw/cmssw#36559
I will test in cms-sw/cmssw#36559
=> reco comparisons: add plots for new MTD value maps; add basic monitoring of JECs in pat::Jets

reco_profiling/profileRunner.py
In order to profile a T0-like workflow (see https://github.com/cms-sw/cmssw/issues/36282) for each release, we needed to update the reco profiling script. The changes were successfully tested for 12_3_0_pre1 and pre2: https://cmssdt.cern.ch/jenkins/job/release-run-reco-profiling/
This has no effect on other functionality of the bot outside the reco profiling.
=> Update the reco profiling script to support an 8-threaded workflow

comparisons/validate.C
Based on the new branch `pat::Muon::mvaIDValue()` from https://github.com/cms-sw/cmssw/pull/36179, add this to `validate.C`.
cc @slava77 @clacaputo
=> Add new muon MVA value from #36179

categories_map.py
In https://github.com/cms-sw/cms-bot/pull/485 reco was added as a signature to EventFilter/Utilities, but it is my understanding that we only follow one file in this package: https://github.com/cms-sw/cmssw/blob/master/EventFilter/Utilities/plugins/TcdsRawToDigi.cc.
Here I propose to remove the reco sig from the full package.
Is there a way to follow automatically only one file from the package?
@cms-sw/reconstruction-l2
=> Remove EventFilter/Utilities from reco

comparisons/validate.C
Track `reco::Photon::haloTaggerMVAVal()` for https://github.com/cms-sw/cmssw/pull/36901.
=> track reco::Photon::haloTaggerMVAVal

githublabels.py, process_pr.py
This allows bot to add new type labels e.g. `type name1(,name2|)` . Existing type labels were `bug-fix` and `new-feature`. This PR also added 
- `documentation`
- `performance-improvements`
- `new-idea` : but may be we do not need this in favor of existing `new-feature`
FYI @qliphy  @perrotta
=> support for adding new type labels

comparisons/analyzeFWComparison.py, comparisons/filter-failed-comparison.py, gen-relval-jobs.py, jobs/create-relval-jobs.py, jobs/jobscheduler.py, jobs/stats.py, jobs/workflow_final.py, logUpdater.py, mark_commit_status.py, pr_testing/get-merged-prs.py, pr_testing/run-das-query.py, pr_testing/run-pr-comparisons, pr_testing/test_multiple_prs.sh, report-pull-request-results.py, run-ib-addon.py, run-ib-relval.py, run-ib-testbase.sh, runTests.py
these script are those which we run during PR tests and IB build. We are missing `python3` on `slc6` and `python` on `rhel8 & cs9` . So initially we created a wrapper script `python3or2` and include it in `PATH` now we propose to replace it with this special code fragment to avoid dependency on external `python3or2`
=> drop usage of python3or2 and find the correct python to run

crab/ib-run-crab.sh
Currently _ib-run-crab.sh_ only submit the job but does not wait for the results. This change consists of a loop to keep checking the status of the job until it finishes.
=> Update ib script for crab to wait for the results

category-watchers.yaml
As conveners of the HLT-Upgrade group, we need to make sure any changes to Upgrade code do not break the HLT Phase-2 menu that has now been integrated in CMSSW.
=> Adding Stephanie and Thiago to upgrade watchers

categories_map.py, watchers.yaml
**PR Description**
This PR adds the `db` signature to the `DQM/BeamMonitor` package.
The rational behind this addition is that the BeamMonitor code is currently the only DQM client running live in P5 that has directl access to upload payloads to CondDB, hence we (@cms-sw/db-l2) would like to add the `db` signature in order to be informed of any possible change.
I hope our DQM colleagues (@cms-sw/dqm-l2) agree with this proposal.
**EDIT**
I profit of this PR to update my personal watchlist.
=> Add `db` signature to DQM/BeamMonitor

run-ib-igprof
On el8 igprof memory profiling with cmsRunGlibC produces empty results. 
This is possibly because of a difference in glibc memory functions.
=> Revert to memory profiling with cmsRun instead of cmsRunGlibC

categories.py
Please @santocch confirm that this corresponds to what you were asking.
analysis category will remain fully uncovered after this removal: remaing packages in that catecory should be re-assigned to other categories to allow the PRs being signed
=> Remove Attilio from analysis signature

reco_profiling/profileRunner.py, run-ib-igprof
Something in Igprof's instrumenting of fork causes an error in `cling::CIFactory::createCI()`
The workaround for now is to execute the command that createCI runs to get the compiler paths and add those to ROOT_INCLUDE_PATH.
```
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
LC_ALL=C g++   -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
/cvmfs/cms-ib.cern.ch/nweek-02734/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-redhat-linux-gnu/10.3.0/../../../../include/c++/10.3.0
/cvmfs/cms-ib.cern.ch/nweek-02734/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-redhat-linux-gnu/10.3.0/../../../../include/c++/10.3.0/x86_64-r …
```
=> When running igprof ensure that compiler include paths are added to ROOT_INCLUDE_PATH 

category-watchers.yaml
Adding @ChrisMisan as watcher of `alca` since he will soon start as AlCa L3 Software Coordinator (once he will officially start we will update `categories.py` as well).
FYI @malbouis @tvami
=> Adding Chris to alca watchers

categories_map.py
Add new packages related to Alpaka and portable data formats to the "heterogeneous" category:
- `HeterogeneousCore/AlpakaServices`
=> Add new heterogeneous packages

categories_map.py
Adding `SimPPS/DirectSimProducer` to the `simulation` category, in line with https://github.com/cms-sw/cmssw/pull/38280
=> New SimPPS/DirectSimProducer subpackage for simulation 

categories_map.py
As per comment https://github.com/cms-sw/cmssw/pull/39029#issuecomment-1211900500
and as it is close enough.
@cms-sw/alca-l2 please confirm if you agree.
=> move `MuonAnalysis/MomentumScaleCalibration` from analysis to alca, in absence of an analysis signature

categories_map.py
This changed is required by PR https://github.com/cms-sw/cmssw/pull/38341 , since it creates a new package L1Trigger/TrackerTFP/
=> Added TrackerTFP to category l1

categories.py
update TRK DPG and TRK POG lists with conveners as of 1st Sept 2022.
@vmariani @sroychow @tsusa please shout if you disagree ;)
=> clean-up TRK DPG / POG categories

jenkins/parser/jobs-config.json
Based on failure in [`build-any-ib` CMSSW_12_6_X_2022-09-06-2300 - el8_ppc64le_gcc10](https://cmssdt.cern.ch/jenkins/job/build-any-ib/136942/)
=> [Jenkins parser job] Add new git error to parser and remove ib-tag-and-schdule

categories_map.py
Adds the new package `CUDADataFormats/PortableTestObjects` introduced in https://github.com/cms-sw/cmssw/pull/39319 .
=> Add `CUDADataFormats/PortableTestObjects` under `heterogeneous`

jenkins/parser/jenkins-parser-job.py, jenkins/parser/jobs-config.json
This PR solves the issue of the parser job sending multiple emails if a new running build (having a build number grater than the parser's last processed build) runs for more than the specified maximum running time (`maxTime` in `jobs-config.json`).
Maximum running times for `ib-run-igprof` and `ib-run-pr-tests` have been also extended.
=> [Jenkins parser] Remove new running builds from list of pending builds 

jenkins/parser/jenkins-parser-job.py, jenkins/parser/jobs-config.json
The fix is already running in Jenkins for testing purposes in https://cmssdt.cern.ch/jenkins/job/jenkins-test-parser/17230/ and runs successfully.
It fixes jobs like [ib-run-HLT](https://cmssdt.cern.ch/jenkins/job/ib-run-HLT/), where Jenkins is configured to self-retry if the build fails, but it doesn't schedule the retry if the build fails because of connection issues.
@smuzaffar, do you have any other suggestion rather than hardcoding the regex _Remote call on .* failed_?
=> [Jenkins parser] Add options to force retry and to check concrete error message in all jobs

groups.yaml
Removing Oz and adding Matej to the pixel-offline group
@OzAmram @mroguljic
=> Update for pixel-offline

jenkins/parser/actions.py, jenkins/parser/helpers.py, jenkins/parser/jenkins-parser-job.py, jenkins/parser/jenkins-retry-job.py, jenkins/parser/jobs-config.json, jenkins/parser/paser-config-unittest.py
Refactor of the jenkins parser into modules.
The retry logic is the same, but we loop inside the parser file doing just one read operation of `parser-info.json` at the beginning of the run (`parser-info.json` is the file where we keep information of the running builds and the last parsed log of each job).
Notification information is stored in memory and saved at the end of each iteration.
There is a default section in `jobs-config.json` with two new options:
- `forceRetry`: You can force retry the failed build even if Jenkins already retries it.
- `allJobs`: Check a concrete error regex in all the jobs.
These modifications are already running in Jenkins.
=> [Jenkins parser] Fix continuous notifications and code refactor

run-ib-igprof
This will check if a workflow is defined in an IB release and warn if it is not, skipping the runTheMatrix.py command.
fixes https://github.com/cms-sw/cms-bot/issues/1854
=> run-ib-igprof script: check if workflow exists in release 

reco_profiling/profileRunner.py
Add two new workflows to profileRunner:
140.56:  real data with 8 threads
159.03:  Production-like MC workflow (i.e., no validation) with memory profiling enabled
These workflows have already been run using my own fork/branch and the output added to the results webpage.
=> Add heavy ion workflows to profiling

jenkins/parser/actions.py, jenkins/parser/helpers.py, jenkins/parser/jenkins-parser-job.py, jenkins/parser/jenkins-retry-job.py, jenkins/parser/jobs-config.json, jenkins/parser/paser-config-unittest.py
This PR adds a new action `retryLate` that will delay the retry by 10 min. This is useful when the failure is due to server error, where an immediate retry will fail as well.
It also adds new failures and jobs to the config file.
The option for triggering the creation of grid nodes is disabled for debugging purposes.
=> [Parser] Add `retryLate` action to delay parser retries

common/github_reports.sh, crab/ib-monitor-crab.sh, crab/ib-run-pr-crab.sh, pr_testing/_helper_functions.sh, pr_testing/test_multiple_prs.sh, report-pull-request-results.py
Follow-up PR for https://github.com/cms-sw/cms-bot/pull/1874
=> [CRAB] Trigger unittest in case of CRAB updates

jenkins/nodes-status-summary.sh
This PR extends the current daily summary of nodes that are still offline and adds the nodes that are still blacklisted. Lines 17-28 correspond to the script that was already sending the offline summary, but I have merged both checks into same script (previously it was directly running on the Build section in the Jenkins job).
Job: https://cmssdt.cern.ch/jenkins/view/All/job/nodes-status-summary/
=> Add blacklisted nodes to daily summary of nodes status

jenkins/connect.sh, jenkins/jenkins-check-nodes.sh, jenkins/nodes-sanity-check.sh
This job runs a check that makes sure `/afs`, `/cvmfs`, `/cvmfs/cms.cern.ch`,  `/cvmfs/cms-ci.cern.ch`,  `/cvmfs/cms-ib.cern.ch`,  `/cvmfs/grid.cern.ch` and `/cvmfs/unpacked.cern.ch` are mounted and that `singularity` can start a container in the node. It runs on `lxplus7`, `lxplus8` and `lxplus9` considering the available hosts at the time of running and both `aarch64` and `ppc64le` machines.
If any of the checks fails, it sends an email notification and writes the node name into a blacklist. For `lxplus` nodes, this blacklist is checked before connecting any node to make sure Jenkins does not connect to a blacklisted node. For `aarch64` and `ppc64le` machines, it takes the corresponding nodes offline.
The blacklist is cleaned up for lxplus nodes if the tests run again successfully in …
=> Nodes `/afs`, `/cvmfs` and `singularity` sanity check

logRootQA.py, pr_testing/run-pr-comparisons
Change in `run-pr-comparisons` is a temporary to allow cms-sw/cmssw#40106 to get integrated. Once cms-sw/cmssw#40106 is 
integrated and PRs start using IBs with cms-sw/cmssw#40106 then we can remove this change.
Also it enable checking edmEventSize for all root files ( except inDQM.root).
=> Allow relval comparsion to have long and short names

jenkins/jenkins-check-nodes.sh
This PR adds the option of testing one single lxplus node setting the boolean parameter `TEST_SINGLE_LXPLUS_HOST` to true. It also includes a special cleanup for non x86_64 (now it will only bring nodes online again if the offline reason is known, so in case one of the nodes is offline because of a different reason, e.g., building Spack, it won't bring the node online). Finally, `node-online` action on lxplus nodes brings the node online, but it stays connected to the buggy host. That is why we now send a `connect-node` action also so that jenkins runs the `connect.sh` script again avoiding the blacklisted host.
=> Fixes and improvements in nodes-sanity-check job

cmssw_known_errors.py
We want to keep relvals wf  `10804.31` and `10805.31` as known errors in non-amd64 archs for the new  CMSSW_13_* release cycle. This will avoid showing TritonService server fallback errors in relvals as reported in https://github.com/cms-sw/cmssw/issues/37767.
=> Add wf `10804.31` and `10805.31` to known errors for release CMSSW_13_* also

categories_map.py
add packages and subsystems to be labeled for tracking
- "CUDADataFormats/Track",
- "DataFormats/Track",
- "RecoPixelVertexing",
- "RecoTracker",
- "RecoVertex",
- "TrackPropagation",
- will also match to TrackPropagation/SteppingHelixPropagator, which is mostly muon reco, but it's probably still OK for tracking
- "TrackingTools"
- will also match TrackingTools/TrackAssociator, which is not tracking, but the alternative is to write a much longer list. So, we could probably unassign
@mmusich 
do you have any comments?
=> add labeling for tracking

categories_map.py
after #1918 the match became more inclusive than originally intended.
I added a trailing `/` to entries that initially corresponded to subsystem names
I'm not sure if a leading `^` is needed in each line.
=> add a trailing / in subsystem names for CMSSW_LABELS

category-watchers.yaml
This PR removes @trtomei (former HLT-Upgrade convener) and @beaucero from the watchers of `upgrade` packages.
The HLT-Upgrade conveners, Stephanie (@beaucero) and Soham (@SohamBhattacharya), only intend to monitor PRs touching the HLT Phase-2 menu (i.e. `HLTrigger/Configuration/python/HLT_75e33*`), and I will notify them manually in the relevant PRs until there is a better solution.
~~This PR makes the conveners of the HLT-Upgrade group, Stephanie (@beaucero) and Soham (@SohamBhattacharya), watchers of the HLT Phase-2 menu in CMSSW.~~
~~It also removes @trtomei (former HLT-Upgrade convener) and @beaucero from the watchers of the "upgrade" packages.~~
Agreed offline with @beaucero. 
FYI: @cms-sw/hlt-l2 @silviodonato
=> remove `beaucero` and `trtomei` from `upgrade` watchers

watchers.yaml
Follow-up of #1920. After #1922, entries in `watchers.yaml` can be used to watch CMSSW changes at file level.
This PR enables automatic notifications to the conveners of the HLT-Upgrade group, Stephanie (@beaucero) and Soham (@SohamBhattacharya), for PRs involving the HLT Phase-2 menu in CMSSW.
Agreed offline with @beaucero.
FYI: @cms-sw/hlt-l2 @silviodonato
=> make `beaucero` and `SohamBhattacharya` watch the HLT Phase-2 menu

github_utils.py, report-build-release-status, report-build-release-status.py
https://github.com/PyGithub/PyGithub versions are either available for python2 or python3. The one we have deploy for bot is based on python2. So during the release build process if `python` ( i.e. python2) is missing either on the host or in the container then release build jobs fails. e.g. `python` missing in
- machines with centos stream8/almalinux8/rhel8 OS
- cmssw/el9 containers
This change drops the usage of `PyGithub` and make use of our `github_utility` api calls.
This is being tested by el9_amd64_gcc11 build of CMSSW_13_0_2 ( https://cmssdt.cern.ch/jenkins/job/build-release/3834/console ). If that `el9` builds goes fine then we should merge it
=> Drop dependency on PyGithub external package for release build process

pr_testing/setup-pr-test-env.sh, run-ib-testbase.sh, system-overrides.sh
In ASAN IBs , some unit tests fail as `LD_PRELOAD=libasan.so` and some system command do not work well. For example `ps` commands hangs when  `LD_PRELOAD=libasan.so`  is set causing few tests to hangs for 3hours. This change allow the bot to conditionally override these system commands in such a way that it unset the LD_PRELOAD and then call system command.
hanging of `ps`  under `libasan` is known issue 
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90589 
- https://sourceware.org/bugzilla/show_bug.cgi?id=27653
=> override system commands for special IBs e.g ASAN

categories_map.py, watchers.yaml
As discussed during the approval of [PR 38226](https://github.com/cms-sw/cmssw/pull/38226) a new package is created and assigned to @cms-sw/xpog-l2
=> Add DPGAnalysis/MuonTools and assign it to xpog

categories.py
Adding new L2 convenors for EGM POG and PF group. 
The old L2s are not removed as we are in overlap period until end of August.
FYI @cms-sw/egamma-pog-l2 and @cms-sw/pf-l2, @RSalvatico
=> Adding new L2s for EGM and PF in `categories.py`

categories.py
Having added a line in which I can sign for "alca" and "db" had overwritten my "operations" category. This should restore it (and I'll remove as soon as I will not be ORP any more)
=> Allow back "operations" signature for perrotta

jenkins-jobs/git/git-notify-ib-updates, shift/libib.py, shift/report.py, shift/uniq-errors.py
Get unique errors in a given IB. Example usage:
```
$ python uniq-errors.py -a el9_amd64_gcc13 -s CMSSW_13_3_X -d 2023-07-28-2300
```
Can also filter out specific error:
```
$ python uniq-errors.py -a el9_amd64_gcc13 -s CMSSW_13_3_X -d 2023-07-28-2300 -f array-bounds
```
=> New tool: uniq-errors

reco_profiling/profileRunner.py
The phase 2 D98 workflow was added to `cmssw-pr-test-config` in #2011 
The PR adds it also to `profileRunner.py`
=> Add D98 wf to profile runner

jenkins_monitor_queue.py
Hello,
This script monitors the jenkins queue and looks for the buggy offline nodes (i.e., the nodes that are kept offline in Jenkins and we need to manually launch them).
We are seeing this type of errors more often, so I think this monitoring will help in detecting the nodes.
As discussed, there is a fist job that runs a simple check daily on every node (https://cmssdt.cern.ch/jenkins/view/All/job/jenkins-infrastructure-sanity-check/).
Then the monitoring job (https://cmssdt.cern.ch/jenkins/view/All/job/jenkins-monitor-queue/) runs every hour and reports offline nodes to OpenSearch. Offline buggy nodes can be found in the Jenkins Grafana Dashboard (https://monit-grafana.cern.ch/d/83t0M504k/cmssdt-jenkins?orgId=11) with the total offline time (in minutes), if there is any buggy node.
=> Monitor jenkins queue and offline nodes

get-relval-failures.py
It goes along with https://github.com/cms-sw/cms-docker/pull/210.
It gets the relval failures from OpenSearch. This information is used to not fail jobs if relvals are failing also in IBs.
=> Get failing relvals from OpenSearch

es_ib_build_stats.py, es_utils.py, jenkins/jenkins-project-report-to-markdown.py, jenkins/report-jenkins-jobs.py, jenkins_monitor_queue.py, parse_jenkins_builds.py
@iarspider , this should fix all the `jenkins-*`  jobs which run on jenkins master/controller node. Only following jobs use python2. All other `jenkins-*` jobs either do not use `python` or already using python3 [a]
```
jenkins-elasticsearch-monitor
jenkins-monitor-queue
jenkins-projects-report
jenkins-projects-wiki-update
```
[a] jobs alread using python3
```
jenkins-backup
jenkins-test-parser
jenkins-test-parser-monitor
jenkins-test-retry
```
=> Py3: Changes required for all all jenkins-* jobs run on jenkins controller

watchers.yaml
Marco Rovere (@rovere) takes up the baton from Stephanie Beauceron (@beaucero) as co-convener of the "HLT Upgrade" subgroup of TSG for the term 01/09/2023-31/08/2025 (approved at the Collaboration Board meeting on 2023, [slide 57](https://indico.cern.ch/event/1280997/contributions/5381463/attachments/2667851/4623604/CB144%20June%202023.pdf#page=57)).
The maintaince of the HLT Phase-2 menu in CMSSW is under the responsibility of the HLT Upgrade group, and the conveners are kindly asked to "watch" the corresponding configuration files (see also https://github.com/cms-sw/cms-bot/pull/1923).
=> add `rovere` as watcher of the HLT Phase-2 menu

github_utils.py
remove the deprecated `permission` parameters ( https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#create-a-team ) 
FYI @iarspider
=> github_utils: fix create_team

categories.py, gh-teams.py
Marco Musich (@mmusich) takes on the duty of HLT-software L2 for the term 01/09/2023-31/08/2025 (approved at the Collaboration Board meeting on 16/06/2023, [slide 53](https://indico.cern.ch/event/1280997/contributions/5381463/attachments/2667851/4623604/CB144%20June%202023.pdf#page=53)). @martin-grunewald continues in this role for the same term ([slide 52](https://indico.cern.ch/event/1280997/contributions/5381463/attachments/2667851/4623604/CB144%20June%202023.pdf#page=52)).
(As agreed internally, I will remove myself from @cms-sw/hlt-l2 after a period of overlap.)
=> add `mmusich` as HLT L2

categories_map.py
This PR adds the upcoming ZDC L1 emulator into the categories map as an L1 assignment (no other assignments yet). The ZDC emulator PR can be found here: https://github.com/cms-sw/cmssw/pull/42634
=> Add ZDC L1T emulator to build bot categories as L1's assignment

add-externals-gh-labels.py, create-github-hooks, es/es_git_repo_size.py, es_ibs_log.py, fix-backport-labels.py, gh-teams.py, jenkins-jobs/git/git-mirror-repository, jenkins/jenkins-kill-placeholder-job.py, jenkins_callback.py, process_pr.py, trigger_jenkins_job.py, update-github-hooks-ip
`process_pr` fix is just to remove error (one should always use `open` to open a file). There are more changes required to make `process_pr` fully py3-compatible: I see many calls to `.encode("ascii", "ignore")` and comparision of result with string. This will no longer work, since `encode` returns `bytes` object, which can't be compared to `str` (directly or with a regex). Do you remember why these calls were added?
=> Py3: More changes

categories.py
This PR removes @dpiparo from CMSSW ORP list.
Thanks a lot for all the work and support @dpiparo
=> Remove dpiparo from the CMSSW L1/ORP list

categories_map.py, watchers.yaml
FYI @clelange @lenzip @vlimant 
- Added PhysicsTools/NanoAODTools under @cms-sw/xpog-l2 
- Added @clelange @lenzip as watcher for PhysicsTools/NanoAODTools
See https://github.com/cms-sw/cms-bot/issues/2043 and https://github.com/cms-sw/cmssw/pull/42323
Fixes https://github.com/cms-sw/cms-bot/issues/2043
=> Added PhysicsTools/NanoAODTools under xpog and update watchers

process_pr.py
This change should allow bot to use cmssw package names to assign categories to an issue e.g. following comments should allow bot to properly assign L2 categories to an issue
```
assign|unassign Package/Name[,Package/Name[...]]
assign|unassign from Package/Name[,Package/Name[...]]
assign|unassign package Package/Name[,Package/Name[...]]
```
@Dr15Jones requested this feature and I agree that it is very useful (avoid doing a lookup in https://github.com/cms-sw/cms-bot/blob/master/categories_map.py to find the package/category mapping)
=> allow assigning of categories using package name

categories.py
Update of the ```categories.py``` file, adding @MartinaMalberti as new MTD DPG L2 conveners. @parbol , former DPG convener, is kept as software support for the MTD DPG.
=> Add Martina Malberti as new MTD DPG L2 convener

categories.py, gh-teams.py
My term as HLT "L2" ended in September (see also https://github.com/cms-sw/cms-bot/pull/2051). After a transition period of a few weeks, I can now be removed from the corresponding lists.
FYI: @cms-sw/hlt-l2
=> remove `missirol` from HLT `cmssw`-L2s and `hlt-confdb` owners

github-rate-limits.py
API remaining calls, limit, and reset time are pushed to the new index `cmssdt-github-api-*` on OpenSearch
Running on Jenkins under https://cmssdt.cern.ch/jenkins/view/All/job/github-monitor-api
=> Push GitHub API Rate Limits to ES

githublabels.py
bot should add label `root`  if `type root` comment is added by orp, l2's
=> add root label

report-pull-request-results.py
Some time relvals failed with `A fatal system signal has occurred: external termination request`  after timeout. this change should look for those Relvals and properly report those in the PR result summary comment
=> look for relval logs with fatal system errors

process_pr.py
This change should add non-blocking labels for `assign Package/Name` comments
=> add non-blocking labels for assign package comment

create-gh-issue.py
The default behavior will be the same. By setting `-q True`, we can avoid commenting on the existing issue.
=> Add a parameter to disable comments on existing GH issues

categories_map.py
Including Geometry/HGCalMapping in categories_map.py under "geometry"
=> Including Geometry/HGCalMapping in categories_map

process_pr.py
We have recently introduced state-based labels that represent the states of a process. To set these labels consistently, we will use the `state <label>` or `build-state <label>` form in the issue comments to tell bot to add the state labels.
=> Allow using `type`, `state` or `build-state` to set labels in GitHub

process_pr.py
=> [draft] Mark all new commits as having no files on clean squash

mass-update-cache.py
@smuzaffar for a single-use script, I see no reason to merge it. I will create and run Jenkins job after you review this.
=>  Script to mass-update bot cache in all issues 

gh-teams.py
In #2104, I was maybe too quick removing myself from `configdb-owners`.
Having write-access to https://github.com/cms-sw/hlt-confdb would allow me to deploy updates to the test/beta instances of the ConfDB GUI to help @cms-sw/hlt-l2 validate changes like the one discussed in https://github.com/cms-sw/hlt-confdb/pull/85.
@cms-sw/hlt-l2 , is this okay ?
=> add (again) `missirol` to `configdb-owners`

process_pr.py
This avoids an extra api call if milestone is already set to correct number.
FYI @iarspider
=> process_pr: bug fix use milestone number instead of id

github_utils.py, process_pr.py
FYI @iarspider , hopefully this should fix the extra github api call for commits.
Also avoid github api calls if linked PRs are from the same repostiory
=> avoid extra commits/repos github api call

process_pr.py
Every time bot runs (even if there are no changes for PR or issue) bot make an api call to get gihtub user name. This change proposes to use only github user login instead of user login + user name. So after this change bot will post message like 
```
A new Pull Request was created by @smuzaffar for branch master.
```
instead of
```
A new Pull Request was created by @smuzaffar (Malik Shahzad Muzaffar) for branch master.
```
If we want to keep the user name then we can update bot to only generate the comment messages when needed e.g. if bot has already seen the issue/PR then no need to execute https://github.com/cms-sw/cms-bot/blob/master/process_pr.py#L2322-L2345 code.
=> Drop user name (user login is enough) from bot messages to avoid one api call

cms-docker-gh-issues.py
This PR modifies the exit codes that are then handled in the Jenkins job. With the new values, if there is any error when running the script, the Jenkins job will nicely clean up the corresponding property files.
=> Modify exit codes for cms-docker building issues

crab/ib-monitor-crab.sh, crab/ib-run-crab.sh
CRAB jobs for IBs have been failing for a while. We initially thought there was some delay in the service, but having a closer look it seems we were having some issues with the certificate:
```
+ curl -X GET --cert /tmp/x509up_u22527 --key /tmp/x509up_u22527 --capath /etc/grid-security/certificates/ 'https://cmsweb.cern.ch:8443/crabserver/prod/task?subresource=search&workflow=240222_165649:cmsbot_crab_Jenkins_CMSSW_14_1_X_2024-02-21-2300_el8_amd64_gcc12_4503'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (58) could not load PEM client certificate, OpenSSL …
```
=> Fix for failing CRAB jobs in IBs

process_pr.py
Base64-encoded data is formatted into lines of 64 characters, lines separated by new-line character. Without `re.DOTALL`, new-line character is not matched by regular expression `.` - so bot cache was not loaded and, more important, it was not overwritten, but appended, quickly exceeding comment length limit.
=> Hotfix for handling compressed bot cache

github_modified_files.py
@smuzaffar Maybe we should also skip notifying L2s for them (as if no-notify "flag" is set in PR message)? We can listed for `ready_for_review` action in `pull_requests` hooks and run a trimmed down version of `process_pr` (just check whom to notify and post a notification comment) when a draft PR is marked "ready for review"?
=> [RFC] Ignore draft pull requests when building a list of modified files

githublabels.py
Fixes #2192
- Added `hlt-integration` type label (with `hlt-int` as short)
- cleanup (define label colors in one place)
=> Added new hlt-integration label plus some cleanup

forward_ports_map.py
FYI, @cms-sw/orp-l2 , as suggested, this will enable the forward porting for 13.0.X to 13.0.HeavyIon.X
=> Enable 13.0.X forward porting to 13.0.HeavyIon.X

jenkins/jenkins-check-nodes.sh, jenkins/nodes-sanity-check.sh, jenkins/parser/jenkins-parser-monitor-job.py
These changes allow to display the offline reason in the monitor table as follows:
=> [NODES SANITY CHECK] Add offline reason to monitor page

categories.py
Adding Afiq Anuar (@afiqaize) as new EGM L2 and removing Anshul Kapoor, who left CMS.
=> Add Afiq Anuar as new EGM L2

categories_map.py
This PR adds upgrade to the `L1Trigger/L1TMuonOverlapPhase2` (phase 2 OMTF) package for https://github.com/cms-sw/cmssw/pull/44557
=> Add upgrade to L1Trigger/L1TMuonOverlapPhase2

pr_testing/run-pr-comparisons
This should fix the issue reported [here](https://github.com/cms-sw/cmssw/pull/44767#issuecomment-2087482148). There was a typo (`-gt` instead of `-eq`) and bot should have ignored the extra failed workflows ran in the baseline.
=> ignore ref wf failures if Pr tests did not run that wf

report-summary-merged-prs.py
@smuzaffar result.arch is set to  `undefined` in the links for vtune. This should return the arch/workflow needed for the Vtune link.
=> Vtune link has undefined for arch

pr_testing/test_multiple_prs.sh
use all relvals after merging PRs for input-relval tests. Thsi should avoid runing relvals which are removed in the PR itself
=> use relvals after PR merge for input tests

lumi/get_slot.sh
Using a different `/scratch/$SLURM_ACCOUNT/$USER/$SESSION` path for each OS. Create CVMFS cache and scratch area if needed.
=> Use different paths for each LUMI slot in Jenkins

cvmfsInstall.sh
Some RPMs (e.g. cms+data-SimG4CMS-Calo+V03-05-00-1-1.el9_amd64_gcc12.rpm) are larger than 2M limit, causing CVMFS publication to fail.
=> Remove downloaded RPMs before publishing

categories_map.py
Adding new package to `daq` supervision.
Package is submitted to CMSSW here:
https://github.com/cms-sw/cmssw/pull/45350
Old DAQ packages that no longer exist in the CMSSW codebase (Run1 period) are cleaned up.
=> Add L1TriggerScouting/OnlineProcessing to DAQ and cleanup old packages

chk-invalid-headers.py
- file in PackageA/SubpackageA can include any file from that subpackage, but only interface (public header) from other package or subpackage
- file in PackageA/SubpackageA/test can, in addition, include file from any other package's `test` directory
=> Relax chk-invalid-headers checks to match SCRAM rules:

pr_testing/_helper_functions.sh, pr_testing/test_multiple_prs.sh
Run `cmsset_default.sh` under `bash -ex` or `zsh -ex` for all supported containers to make sure it runs without errors.
=> PR test: Run sourcing of cmsset_default.sh for el6-el9

create-github-hooks.py, github_hooks_config.py
Github has updated the API for creating/updating webhooks and now it does not allow to add any arbitrary data to be added in hook.config. We previously we were adding hook name and hook extra data in to it to check if a hook needs to be updated ( e.g. due to url change or secret update). Now use add `name and  data` in to hook URL
=> update github create hook: include name and data in to url

githublabels.py
This should allow to add `changes-dataformats` label by an explicit comment by L2/ORP
See https://github.com/cms-sw/cms-bot/issues/2245 for the request
=> allow to add changes-dataformats labels by an explicit comment by L2/ORP

categories_map.py, process_pr.py
See https://github.com/cms-sw/cms-bot/issues/2245 for details
=> add changes-dataformats label if PR touches classes_def.xml

watchers.yaml
I was recently appointed as co-convener of the "HLT Upgrade" subgroup of TSG from September 1st, 2024, to August 31st, 2026 (approved at the Collaboration Board meeting on 28/06/2024, [slide 23](https://indico.cern.ch/event/1421824/contributions/5978945/attachments/2886784/5059648/CB149%20June%202024%20.pdf#page=23)).
The maintenance of the HLT Phase-2 menu in CMSSW is under the responsibility of the HLT Upgrade group, and, to that purpose, I would like to be added as a watcher for the corresponding configuration files.
PR made after coordinating with @missirol.
=> Add VourMa as watcher of the HLT Phase-2 menu

categories.py
@cms-sw/orp-l2 , this PR adds @mandrenguyen as ORP for CMS offline & Computing
@mandrenguyen , once merged, you will become owner of cms-sw , cms-data and cms-externals github organization. This will allow you to directly push changes to any repository under these organizations. As you are also L2 of reconstruction so simple `+1` on PR will sign that PR for both reconstruction and orp. I would suggest to use `+reconstruction` and `+orp` to separately sign PRs.
=> Added @mandrenguyen as new ORP manager

docker_launcher.sh
As discussed in https://github.com/apptainer/apptainer/issues/2328 , we think issue with failures like 
```
FATAL:   container creation failed: mount hook function failure: mount /etc/tnsnames.ora->/etc/tnsnames.ora error: while mounting /etc/tnsnames.ora: destination /etc/tnsnames.ora doesn't exist in container
```
are due to the update of `/etc/tnsnames.ora` on host by puppet.
This PR proposes to make a copy of /etc/tnsnames.ora and then mount that copy in side container. This why any update of /etc/tnsnames.ora by puppet will not change the mounted copy. 
This might be a fix/workaround for the https://github.com/cms-sw/cmssw/issues/45501 issue
=> make a copy of /etc/tnsnames.ora before starting the container

categories_map.py
The GeometryAligner.h has to be moved from Geometry/CommonTopologies to avoid unusual dependencies
=> Update categories_map.py to assign category for GeometryAligner

categories_map.py
This PR add the new DQMOffline/ParticleFlow package in the [categories_map.py](https://github.com/cms-sw/cms-bot/blob/master/categories_map.py), introduced by the PR https://github.com/cms-sw/cmssw/pull/45667 .
@jroloff @swagata87
=> Add Particle Flow DQM package to CMSSW categories

process_pr.py
@smuzaffar I think this change makes sense - we only need to check what files were touched to determine what L2 signatures the PR needs, right?
=> [RFC] Disable checking for number of modified files in non-cmssw repos

jenkins/jenkins-check-nodes.sh, jenkins/parser/actions.py, jenkins/parser/jenkins-parser-job.py, jenkins/parser/jenkins-parser-monitor-job.py, jenkins/parser/jenkins-retry-job.py
I fixed all the places I saw 'appropiate' in cms-bot, and I don't think it's parsing any output for this specific misspelled word from other projects like CMSSW.
=> Fix one misspelled word in Jenkins parser

process_pr.py, tests/PRActionData/TestProcessPr.test_assign.json
I noticed in https://github.com/cms-sw/cmssw/issues/46113 that the list of tagged L2s could contain duplicates when multiple categories are assigned.
I chose the most broadly compatible approach (works across Python 2 and 3) to remove the duplicates, preserving the order to be as consistent as possible with previous behavior. Tested in standalone Python and it works as expected.
=> avoid duplication in l2 list

pr_testing/test_multiple_prs.sh
As suggested here: https://github.com/cms-sw/cmssw/pull/46388#issuecomment-2421667896
=> PR Testing: check for warnings also in files not directly touched by PR

pr_testing/test_multiple_prs.sh
Reverts cms-sw/cms-bot#2361
@iarspider , I am reverting it for now
=> Revert "PR Testing: check for warnings also in files not directly touched by PR"

docker_launcher.sh
This should fix Risc-V builds. @smuzaffar as discussed.
=> Set TMPDIR in docker_launcher.sh if not set already

cms_static.py, cmsrep.sh
Testing AuthenticAMD for PR/baseline Relvals (see https://github.com/cms-sw/cmssw/issues/46669)
=> use AuthenticAMD for PR/baselibe relvals

report-pull-request-results.py
=> Only report each RelVal failure once; fix formatting

categories.py, process_pr.py
@cms-sw/orp-l2 , as discussed, this PR should allow to automatically sign `operations` when tests are passed.
=> automatically approve operations on tests passed

githublabels.py
Add the `ngt` label, to support the `type ngt` bot command.
=> Add "ngt" label

comparisons/compare-maxmem-summary.py, comparisons/resources-diff.py
resolves https://github.com/cms-sw/framework-team/issues/1089
resolves https://github.com/cms-sw/framework-team/issues/1152
=> Add tables for the additional  MaxMemoryPreload-reported quantities

buildLogAnalyzer.py
Example: [was](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_15_0_CLANG_X_2024-12-17-2300/Alignment/OfflineValidation) - [will be](https://iarazumov.web.cern.ch/CMSSW_15_0_CLANG_X_2024-12-16-2300/Alignment/OfflineValidation/log.html)
=> Add hyperlinks to build log

jenkins-artifacts
This should ensure that uploaded files will be accessible on the web.
=> send_jenkins_artifacts: ignore source user, group and permissions

pr_testing/test_multiple_prs.sh
Run multiple `runTheMatix` commands if extra relvals requires different command-line options
=> improve running of pr relvals

pr_testing/test_multiple_prs.sh
This should fix the PR tests for old release cycles which use pkgtools V00-31-XX where `cmsBuild` does not support `--define` command line option
=> cmsBuild from V00-33 and above support --define option

repos/Eric100911/collatz/repo_config.py
🔧  Already set up token and other configs.
=> :sparkles: Begin trying CI on cmsbot from Eric100911/collatz

jenkins/system-info.sh
@smuzaffar as discussed. We should keep the old `nvidia` label for now, until all jobs are configured to use `cuda` and/or `rocm` labels.
=> Add 'cuda' label; detect AMD gpu and assign 'rocm' label

docker_launcher.sh
See https://cms-talk.web.cern.ch/t/voms-proxy-and-token-issuer-service-change/42807/3
=> override voms-cms-auth.app.cern.ch to avoid using voms-cms-auth.app.cern.ch

cleanup-cmssdt, cmssw-pr-test-config, gpu_flavors.txt, pr_testing/_helper_functions.sh, pr_testing/run-pr-comparisons, pr_testing/run-pr-relvals.sh, pr_testing/run-pr-unittests.sh, pr_testing/test_multiple_prs.sh, process_pr.py, report-pull-request-results.py, run-ib-pr-matrix.sh, tests/PRActionData/TestProcessPr.test_abort.json, tests/PRActionData/TestProcessPr.test_draft_pr_ready.json, tests/PRActionData/TestProcessPr.test_draft_pr_start_test.json, tests/PRActionData/TestProcessPr.test_run_test_params.json, tests/PRActionData/TestProcessPr.test_start_tests.json, tests/PRActionData/TestProcessPr.test_tests_passed.json, tests/test-requirements.txt
<cmsbot> </cmsbot>
Additional changes :
=> Run PR gpu utests/relvals on both CUDA and ROCm GPUs

cmsutils.py, pr_testing/test_multiple_prs.sh
- override cpu count via JENKINS_AGENT_CORES
- disable using `maxmem-profile` for rocm tests . Just like we do it for IB relvals https://github.com/cms-sw/cms-bot/blob/master/run-ib-pr-matrix.sh#L67-L69
=> override cpu count via JENKINS_AGENT_CORES

process_pr.py
<cmsbot></cmsbot>
We can't just replace dash with underscode, since we use dash in `multi-microarchs`. If you think that we should use underscoes everywhere, I can do it.
=> Extra tests: accept 'high_stats', not 'high-stats'

process_pr.py
This will useful to validate changes to regexes used to match bot commands. The commented out lines will be part of that future change.
=> process_pr: put code that preprocesses comment text into separate function

categories.py
Add Raffaella Tramontano as new EGM convener. Remove Afiq Anuar, since he left CMS.
=> Add Raffaella Tramontano as EGM convener

kill-stuck-pr-test.sh, parse_jenkins_builds.json, parse_jenkins_builds.py, pr_testing/_helper_functions.sh, pr_testing/run-pr-comparisons, pr_testing/run-pr-relvals.sh, pr_testing/run-pr-unittests.sh, update-commit-statues-matching.py
Split from #2418. For now, job list and criteria for killing builds are hardcoded. We can discuss how configurable do we want this job to be - for example, a dict mapping job name and filters on params to timeout.
=> Automatically kill stuck PR tests and report back

process_pr.py
=> Do not process closed PRs

pr_testing/run-pr-hlt-p2-integration.sh
It was noticed in PR https://github.com/cms-sw/cmssw/pull/47859 that despite there were errors in the logs (see [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-724d13/45600/hlt-p2-integration.log)), the bot still marked it as successful, see [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-724d13/45600/summary.html).
I add a check for errors in the log now and mark the PR tests as failure in case the bot finds any.
=> check for errors in the `hlt-p2-integration.log`

process_pr.py
If `orp` and/or `operations` are the only assigned categories, do not add `fully-signed` label until they sign the issue (or PR).  This fixes the invalid behavior seen in https://github.com/cms-sw/cmssw/issues/47964
=> Fix signing labels for orp-only issues

pr_testing/run-pr-comparisons
Currently the nano comparison report will shows only the WF number. The goal is to have the the full WF name available.
The table:
| Sample | kb/ev | ref kb/ev | diff kb/ev | ev/s/thd | ref ev/s/thd | diff rate | mem/thd | ref mem/thd |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 2500.238 | 2.595 | 2.501 | 0.094 ( +3.8% ) | 13.76 | 13.71 | +0.4% | 2.751 | 2.745 |
Will become:
| Sample | kb/ev | ref kb/ev | diff kb/ev | ev/s/thd | ref ev/s/thd | diff rate | mem/thd | ref mem/thd |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 2500.238_ScoutingNANOwithPromptdata140Xrun3 | 2.595 | 2.501 | 0.094 ( +3.8% ) | 13.76 | 13.71 | +0.4% | 2.751 | 2.745 |
Since I don´t know how to test this proposal in this repo, I'm placing this PR and hoping to test during review.
=> Nano Comparison: Keep WF full name and forward it to .json files

ib-create-tag.py
https://github.com/cms-sw/cms-bot/pull/2480 revealed that we are trying to create same reference twice, [e.g.](https://cmssdt.cern.ch/jenkins/job/ib-tag-and-schdule/9355/consoleFull):
```
create_git_tag(cms-sw/cmssw, CMSSW_15_0_X_2025-04-29-2300, 001b97d2ac867b36ee0fb0273dda20fe6e95f6ed) failed: HTTP Error 422: Unprocessable Entity
Response: {"message":"Reference already exists","documentation_url":"https://docs.github.com/rest/git/refs#create-a-reference","status":"422"}'
```
I think what happens is Github returns 5xx error ("server error"), but since we assume the only error we can get is 404 (i.e. tag doesn't exist) we try to create the reference anyway and fail. 
[Documentation](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#get-a-reference) also mentions code `409 …
=> ib-create-tag: do not fail if trying to create a tag that already exists

run-pr-code-checks
This is temp fix to run code-checks for cmssw PRs. A proper fix should go in to llvm package itself ( e.g. to see why clang-tidy is not getting extra arguments from clang++.cfg)
=> temp fix for running PR code-checks: explicitly set --gcc-toolchain

pr_testing/test_multiple_prs.sh
This change automatically checkouts cmssw `SubSystem/Package` for each `cms-data/Subsystem-Package` PR
=> checkout cmssw packages for cms-data/repo PRs

pr_testing/test_multiple_prs.sh
Use cmsswdata.xml to find out the changed data package instead of `cms-data/Repo` PRs. Thsi way bot can find out changed data packages via cmsdist PR too
=> use cmsswdata.xml to find the changes data packages

pr_testing/run-pr-hlt-p2-integration.sh, run-hlt-validation
Runs the phase 2 integration tests for all HLT menu flavours if the ```--menu``` option (introduced in [#48664 in CMSSW](https://github.com/cms-sw/cmssw/pull/48664)) is supported by ```hltPhase2UpgradeIntegrationTests```. It simply filters the keys present in ```Configuration/HLT/python/autoHLT.py``` with the "Run4" substring.
Tested in my local CMSSW release; further tests are necessary @mmusich.
=> Run all Run4 HLT menu flavours.

repos/iarspider_cmssw/cmssw/watchers.yaml
This file was changed in https://github.com/cms-sw/cms-bot/pull/2552. It should never be changed, otherwise tests will fail.
=> Restore watchers.yaml used for process_pr tests

RelValArgs.py
This PR enables running Relvals of ROOT6 under `cmsTraceFunction`. It also now uses `--abort` to fail the relval step if function e.g. `setenv` is called.
=> run relvals for devel/root6 with cmsTraceFunction --abort

categories.py
We were using the wrong github account for Sercan Sen (GEN Core Software Integration convener).
This PR is fixing the issue.
=> Fix wrong name in the generators category
