cms-sw/cms-bot

categories.py
=> Assign HLTriggerOffline/SMP to DQM

process-pull-request
L2 should still be able to ask for tests.
=> Do not skip commenter for cycle if L2 is not among the singing category

report-summary-merged-prs
This also fixes a case in which the tests are shown green when there are errors.
=> IB Pages: Improve the way the relvals results are read.

categories.py
=> Add @ssekmen as fastsim

scram-package-monitor
Helper script for scram to push information about packages being built to an elasticsearch instance.
=> Introduce scram-package-monitor

comparisons/validateJR.sh
And create one process per available processor.
=> Comparisons: Set timeout while waiting for last processes - JRcomp

categories.py
DataFormats/L1TCalorimeter DataFormats/L1TGlobal are added
=> add  L1 data formats to L1 category

watchers.yaml
For
- AnalysisDataFormats/TopObjects
- TopQuarkAnalysis
=> Watcher request

comparisons/compareValHists.C, comparisons/validate.C
validate.C and compareValHists.C  needed an update to compile and run with ROOT6
I've updated from their original location: https://github.com/slava77/cms-reco-tools
=> update validate.C: works with ROOT6, added new variables

es-cleanup-indexes
=> Adapt to ES 1.5.0

comparisons/validate.C
- some voodoo: add a call to histogram GetMean to get consistent bin ranges and values from the reference plot; otherwise bins get misaligned sometimes and false-positive differences are reported (can be almost all histograms). The fix works on cmsdev02. If this gets merged, can confirm for jenkins as well.
- some cosmetics to the code as well and more informative diff printouts
=>  fix validate.C to run with ROOT6 consistently

DMWM/activate-start-agent.sh, DMWM/deploy-wmagent.sh, DMWM/install-wmcore.sh, DMWM/latest-dmwm-versions.sh, DMWM/temporary-patches.sh, DMWM/test-wmcore.sh, DMWM/update-deployment.sh, DMWM/update-wmcore.sh
This set of scripts gets me through my first Jenkins job. I'd appreciate a review, of course, since this is new to me.
=> A set of scripts to deploy WMAgent and run the WMCore unit test

DMWM/activate-start-agent.sh, DMWM/deploy-wmagent.sh, DMWM/install-wmcore.sh, DMWM/latest-dmwm-versions.sh, DMWM/temporary-patches.sh, DMWM/test-wmcore.sh, DMWM/update-deployment.sh, DMWM/update-wmcore.sh
=> Update DMWM scripts for improved Jenkins testing

DMWM/deploy-wmagent.sh, DMWM/install-wmcore.sh, DMWM/kill-databases.sh, DMWM/setup-cmsbot.sh, DMWM/setup-secrets.sh
=> Newly factored out scripts

releases.map
Signed-off-by: David Abdurachmanov <davidlt@cern.ch>
=> Add CMSSW_7_2_0_pre1 (dev) for fc19_aarch64_gcc490

build-release-watchers.yaml, categories.py, process-build-release-request, releases.py
[![bye](https://docs.google.com/drawings/d/1iy8FSwuLCKx6aVCgP2LZxXolFG4KRfoHLbeGiBifV0o/pub?w=113&h=74)](https://docs.google.com/drawings/d/1iy8FSwuLCKx6aVCgP2LZxXolFG4KRfoHLbeGiBifV0o/pub?w=113&h=74)
=> Decomission @nclopezo

categories.py
https://github.com/cms-sw/cmssw/pull/9802 was merged already without a new category for the package.
=> add Calibration/Hotline to AlCa category

logRootQA.py
Add tool to probe log files and root files to check for printouts and for changes in event content. Just printouts for the moment
=> v1 of new qa tool

DMWM/AggregatePylint.py, DMWM/AnalyzePylint.py, DMWM/CompareTests.py, DMWM/IssueMessage.py, DMWM/xunitparser.py
=> Scripts to add ability to test DMWM pull requests

comment-gh-pr, githublabels.py, process-pull-request
- new script to comment any github pr
- process jenkins jobs failed for ib-any-integration and reset the test status
- github labels colors and names
=> new script and jenkins job failed for ib tests message

DMWM/AnalyzePy27.py, DMWM/AnalyzePyFuture.py, DMWM/AnalyzePylint.py, DMWM/CompareTests.py, DMWM/TestWatchdog.py, DMWM/kill-databases.sh, DMWM/test-wmcore.sh
Truncate GH comments that are too long
Deal with python standard regressions and add future import analysis for new files
Kill off zombies of test suite from other slices and add a watcher to kill stuck tests that have written an XML file
Put BuildID in the nosetest filename
@smuzaffar please merge
=> Lots of changes to DMWM scripts.

DMWM/CompareTests.py, DMWM/TestWatchdog.py
Remove a message, sort unit tests in report, abide by PEP-8
=> Dmwm aug tweak

DMWM/TestWatchdog.py
@smuzaffar can you merge this? Thanks.
=> Upgrade psutils

categories.py
to go with https://github.com/cms-sw/cmssw/pull/11122
=> add RecoBTag/CTagging to reconstruction category

DMWM/AnalyzePylint.py, DMWM/CompareTests.py
Another PR to be merge @smuzaffar . Hopefully will not conflict with the other outstanding one.
=> Ignore unstable

categories.py, watchers.yaml
@smuzaffar Can you please merge this for https://github.com/cms-sw/cmssw/pull/11649
@bsunanda
@sethzenz this includes the changes of your PR to cms-bot please close it.
=> Add Validation/HGCalValidation to categories, update watchers

categories.py, watchers.yaml
@smuzaffar @degano New packages I am about to submit a PR for, better to have watchers and categories in before I submit so the right people are notified.
=> Add categories/watchers for HGCalRecHitAlgos/Producers

watchers.yaml
=> Add Chris Seez (HGC software/perf convener) to HGC watchers

DMWM/CompareTests.py
=> Build a comparison between previous and current UnitTest

DMWM/CompareTests.py
=> Missed a double message. Sorry.

run-cmsdist-tests.sh
Now takes only the PR number to test.
Runs also the Relvals at the end.
=> Expand cmsdist tests.

categories.py
adding 
DataFormats/PatCandidates and PhysicsTools/PatAlgos to RECO
to formalize the updated mandates
@davidlange6 please confirm
=> adding  DataFormats/PatCandidates and PhysicsTools/PatAlgos to RECO

run-cmsdist-tests.sh, run-pr-tests
Update the comment on CMSSW also when testing CMSDIST+CMSSW.
=> Don't update twice the comment when testing CMSDIST only PR.

categories.py
updated reco mandate includes maintenance of miniAOD as well
=> add RecoMET/METFilters to reco as a standard part of miniAOD application

categories.py
This is needed for https://github.com/cms-sw/cmssw/pull/13058
=> add EventFilter/TwinMuxRawToDigi to l1 category

run-cmsdist-tests.sh
=> Force the architecture when listing available releases

run-pr-tests
=> Revert "The PR number for test reports is always only one."

es_relval_log.py
the timestamp name conflict with builtin timestamp variable , updated to tstamp
=> timestamp name changed

es_utils.py, parse_jenkins_builds.py
=> Revert "Check for status change of running builds to stale-deleted added"

categories.py
add @rekovic as maintainer for the L1 Trigger software
=> add @rekovic as maintainer for the L1 Trigger software

categories.py
- DataFormats/TotemRPDetId to simulation
- DataFormats/TotemRPDigi to reconstruction
=> add TotemRP DataFormat packages to categories

categories.py
@mulhearn @rekovic
this will add L1 signatures to #13837 and related
=> DataFormats/L1TotemRP added to L1 category

categories.py
needed for proper tracking of https://github.com/cms-sw/cmssw/pull/14134
@smuzaffar @degano please merge at your earliest
=> add DataFormats/CTPPSReco to reco category

watchers.yaml
This PR to update the list of packages followed by the muon POG conveners (@battibass, @HuguesBrun)
=> update the list of packages followed by muon POG

comparisons/validate.C
comparisons/validate.C updated
- miniaod validation with fwlite  contributed by Devin ( @dntaylor )
- complete PR was https://github.com/slava77/cms-reco-tools/pull/78 . Here I'm including updates only to validate.C . There will be no changes to the results until the driver script is updated (to be done next)
- also, several more minor updates
- PFRecHit position safe from upcoming slimming of the class
- several btag variables
This version was used in local tests. So, expect it to run with jenkins just as well.
=> validate.C updates: miniaod validation with fwlite (partial integration) and a few minor updates

categories.py
needed for proper tracking of https://github.com/cms-sw/cmssw/pull/14605
please merge at your earliest
=> add new RecoCTPPS/ packages to reco

categories.py
New package appeared in https://github.com/cms-sw/cmssw/pull/14148
By now the PR is signed by db already. 
So, this will clear to new-package-pending label and will be useful for code tracking if future updates come
=> add CondTools/BTau to db category

categories.py
Needed by: https://github.com/cms-sw/cmssw/pull/14885
attn: @slava77, @emiglior
=> add DataFormats/Phase2ITPixelCluster package to category

watchers.yaml
For https://github.com/cms-sw/cmssw/issues/15161
=> updates watchers list

groups.yaml, watchers.yaml
Adding new BTV software conveners to the list of watchers and adding a new BTV package to watch
=> BTV updates

watchers.yaml
Dears,
Could I please watch the following package ?
So that I receive notifications whenever the XMLs from tkLayout are incorporated into CMSSW.
(These XMLs are what provide CMSSW a Phase 2 Tracker geometry description. These XMLs are created by tkLayout, from a given design choice (layout) from the Physicists/Engineering teams.)
Thanks,
Cheers,
Gabrielle
FYI : @boudoul
=> Request to watch a package

categories.py
=> add Configuration/Eras to operations

DMWM/setup-secrets.sh
OK @smuzaffar this PR should move us to the certs in ~/.globus
=> Switch where we get our certificates from

categories.py
https://github.com/cms-sw/cms-bot/issues/739
=> adds silviodonato to L2 for hlt

categories.py
I guess I need to add these packages already to label "analysis" for the PR #15484 in cmssw:
https://github.com/cms-sw/cmssw/pull/15484.
=> add new package HeavyFlavorAnalysis to analysis tool area

DMWM/AnalyzePylint.py
This will fix one of our Jenkins error conditions. Please merge
=> Allow for the case where no python files are changed

categories.py
Related PR: https://github.com/cms-sw/cmssw/pull/16099
=> Add DQM/SiPixelPhase1RawData to categories.py

categories.py
Missed in https://github.com/cms-sw/cms-bot/pull/753
=> Add AlCa signature for  "CondFormats/CTPPSReadoutObjects"

watchers.yaml
https://github.com/cms-sw/cmssw/issues/15929
=> adds sviret to watcherlist for packages

categories.py
check with @davidlange6 to approve
=> add makortel to list of PR test triggers

categories.py
Recent #774 missed a comma.
@slava77
=> Fix categories.py by adding a missing comma

watchers.yaml
I am leaving the field and would like to withdraw from receiving notifications. Thanks for the many years of fun!
=> remove richard-cms from watchers

categories.py
Add Arun Kumar as AlCa/DB convener starting Jan 2017
=> Add @arunhep as CMSSW_L2 for alca

categories.py
Following https://github.com/cms-sw/cmssw/pull/17059/#issuecomment-270681331 I add a new package to categories.py
=> Adding L1TriggerConfig/XmlConfigTools package under l1 category

categories.py
@smuzaffar please merge this ASAP, otherwise I can't sign PRs
=> fix username

categories.py
In response to PR https://github.com/cms-sw/cmssw/pull/17327 where this package is introduced.
@idebruyn @ivanpari
=> Add DQM/Phase2OuterTracker to DQM category

categories.py
@sextonkennedy @davidlange6 
@cvuosalo @perrotta
=> perrotta from hlt to reconstruction; drop cvuosalo from reconstruction

logRootQA.py, run-pr-comparisons
this is a bit more involved, so I'll try to watch for failing comparisons. adding some details about histogram comparisons (from the logs) and the JR tests (counting pngs). Still to do is to make a short summary..
=> adding histogram and jr test tally info

categories.py
Title says it all: added to file `categories.py` signatures from `alca` and `db` for added packages:
* `CondFormats/PCLConfig`
* `CondCore/PCLConfigPlugins`
=> Add new packages for PR cms-sw/cmssw#18087

comparisons/validate.C
- add CTPPS diamond digis
- fix CTPPS strip digi names used since 9X
=>  validateJR updates in CTPPS plots

categories.py
=> add ME0Trigger package

comparisons/validate.C
- packedCandidates physics level plots are actually working (they were commented out/broken in early 7X version) ==> uncommented now
- add CTPPS pixel digi plots
=> reco comparisons: add CTPPS pixel digis and muon puppi isolation; recover packedCandidates physics level plots

comparisons/validate.C
- improve packedCand comparisons
- add basic plots of muon matches 
- new products pfDeepCMVAJetTags
=> comparisons updates: add pfDeepCMVA tag and muon matches

run-material-budget
Switch to using the new python version of MaterialBudget script.
=> Fix material validation scripts

run-material-budget
Chaning the script to work either with .C or .py script
=> Updating the run-material-budget script

categories.py
add one new package "DQMOffline/Lumi" under dqm
=> Update categories.py with new package "DQMOffline/Lumi"

categories.py
FYI @mtosi , @davidlange6 and @fwyzard 
Now, mia should be able to trigger the PR tests via "@cmsbuild, please test" command
=> Allow mtosi (mia tosi) to trigger PR tests

categories.py
Luca Pernie will be new AlCa-DB convener starting from September 2017.
It will be good for him to start having a look at the github activity
@franzoni @cerminar @lpernie
=> Adding Luca Pernie as L2 AlCa

watchers.yaml
I would like to watch HGCal related packages.
=> watch HGCal packages

watchers.yaml
Removing my user as EGM package watchers. I will be leaving CMS in August.
=> Remove rafaellopesdesa from list of watchers

comparisons/matrix_RE.txt
wf 7.3 was added to the short matrix recently and an update in the map file is needed.
=> reco comparisons: map cosmics 2017 MC workflows

watchers.yaml
Hello, 
I would like to follow the Egamma related repositories. 
Thank you,
Shilpi
=> Added jainshilpi to watch Egamma related respositories

cmsdist_merge_permissions.py
-privilege to merge updates to PHEDEX and spacemon-client specs  which are independent of cmsweb release schedule
=> allow nataliaratnikova to merge changes for comp branches

comparisons/validate.C
- wrap plots of recoGsfTracks in gsfTrackVars and add plots for electron GsfTracksFromMultiCl (only in phase-2); 
- fix a spelling typo
=> reco comparisons: update plots of gsfTracks

jobs/workflow_final.py, rv_scheduler/JobsConstructor.py, rv_scheduler/JobsManager.py, rv_scheduler/prepareSteps.py
Updating relval scheduler to use the workflow_final script for formatting & fixing the expected logs
=> Relval scheduler update

categories.py
=> adding Alignments/CTPPS to categories.py

watchers.yaml
Added varuns23 to Egamma repositories watch list
=>  add varuns23 to Egamma repositories watch list

jenkins/connectToSlave.sh
Assuring resources are delivered to jenkins slave (ssh keys etc) before connecting
=> Initialize jenkins slave before connecting

templates/showIB.html
- removed broken link to Historical Performance Plots.
- possible to select default page.
=> showIB.html page update

categories.py
Javier Fernandez is our new convener.
@jfernan2
=> Add DQM L2 convener

watchers.yaml
=> Update my watchlist

build-release-watchers.yaml, categories.py, gh-teams.py, milestones.py, super-users.yaml
=> added Fabio Cossutti (@fabiocos) as L1/Release manager

watchers.yaml
Add NanoAOD to gpetruc's watchlist
=> Add NanoAOD to gpetruc's watchlist

es_ibs_log.py, logreaderUtils.py, runPyRelValThread.py, tests/test_logreaderUtils.py
logreader config files are generated when logs are parsed
=> logreader config files are generated when logs are parsed

cmsdist_merge_permissions.py
@h4d4, this replaces @emaszs with @ todor-ivanov for cmsdist permissions
=> updated cmsdist permission

comparisons/validate.C
add plots of user data (ints, floats, isolations, IDs) for leptons and photons
=> reco comparisons updates: add plots of user data for leptons and photons

categories_map.py
Add the package DetectorDescription/DDCMS to the geometry category, after the merge of cmssw PR 22194
=> add DetectorDescription/DDCMS to the geometry category

categories_map.py
Add CalibTracker/SiPixelQuality for SiPixelQuality PCL and monitoring
=> Add CalibTracker/SiPixelQuality into cmssw categories

categories_map.py
=> Adding SiPixelPhase1DeadFEDChannels to the relevant category

watchers.yaml
Following #959, I modified watchers.yaml.
@smuzaffar, thanks.
=> add @echabert as watcher of strip packages

watchers.yaml
Removing myself and old contributors having left: jlagram, cnuttens, lbeck, sdevissc
=> remove jlagram from watching

categories_map.py
having this in reco category was never really particularly practical
@perrotta
=> drop Validation/Configuration from reco category

categories.py, category-watchers.yaml, watchers.yaml
=> Remove 'ghellwig'.

cmsdist_merge_permissions.py
=> Updated cmsdist repo permissions: Removed BrunoCoimbra and added lecriste

watchers.yaml
as tkDQM convener, to follow the tkDQM PR
=> add jandrea to the watchers

groups.yaml
Added new software convener for BTV: smoortga
=> added BTV software convener

categories_map.py
the changes are introduced with https://github.com/cms-sw/cmssw/pull/23033
=> add  RecoBTag/TensorFlow to reconstruction category

categories.py
Hello,
@pohsun is joining AlCa/DB group as our next AlCa/DB software coordinator.
So, please add him as L2 in github for AlCa so that he can sign PRs on behalf of AlCa
Thanks,
Arun.
FYI : @lpernie @ggovi @fabiocos
=> Adding PoHsun as AlCa L2

categories_map.py
Addition of packages introduced first in cms-sw/cmssw#23126 and then used in cms-sw/cmssw#23603
=> Add Geometry MTD packages to the geometry category

watchers.yaml
Please add me to the list of watchers.
=> add clelange as watcher for several JME JMAR related packages

categories_map.py
Add the new CondFormats/SiPixelTransient package, and assign both db and reco as owners
The new package is introduced by #23571
=> Add the new CondFormats/SiPixelTransient package, and assign both db and reco as owners

watchers.yaml
I'd like to watch CTPPS-related packages.
=> Packages for watch by jan-kaspar

categories.py
@fabiocos and @kpedro88 , this PR should allow Kevin the L1 rights. Kevin this means when you say +1 then it will be treated at approval for all categories for which you are L2 and approval for ORP too.
You need to explicitly say +upgrade to sign for individual categories.
=> added @kpedro88 as release manager

categories.py
Under Gianluca request, I removed him from AlCa category.
=> Removed Gianluca from AlCa category

categories_map.py
Add DetectorDescription/DDVecCMS to geometry category
=> add new package to geometry

cmssw_known_errors.py
Fix the 5 inconsistent wfs in 10_3. The known failing remains the same for 10_2.
=> Fix known failing workflows for 10_3

cmssw_known_errors.py
Remove also 555.0 from known errors as it's been fixed https://github.com/cms-sw/cmssw/pull/24341
=> remove 555.0 from known errors for slc6_amd64_gcc700

categories.py
Removing arunhep from AlCa, as he asked.
=> Removing Arun from AlCa

categories.py
Per explicit request of @silviodonato whose mandate has ended in August
=> Remove S. Donato from HLT  L2 authorized signatures

categories_map.py
this is to assign the new package introduced in cms-sw/cmssw#24432
=> add CommonTools/MVAUtils to reco and analysis

watchers.yaml
Would no longer like to follow strip reco packages
=> Update watchers.yml for nickmccoll

comparisons/validate.C
- add hgcalLayerClusters time
- add plots for hiCentrality
=> reco comparisons updates: add hgcalLayerClusters time ; add plots for hiCentrality

categories.py
The XPOG coordinators in charge of NanoAOD have changed from @arizzi and @gpetruc to @peruzzim and @fgolf
=> Change the analysis responsible for NanoAOD

categories_map.py
Was requested in discussion on #24490
=> Removed Utilities/PPS from the list of core

watchers.yaml
Work is being done for Tracker DPG. Adding mylsef to the list of watchers to the following modules:
```
- Configuration/Geometry
- Geometry/TrackerCommonData
- Validation/Geometry
```
FYI @mmusich
=> Add @vargasa to the list of watchers

cvmfs_deployment/cvmfs-cms-install-package.sh
add checks for non empty vars - install path, arch and package name
=> check inputs

categories_map.py
Addition of the new package Utilities/PPS introduced in cms-sw/cmssw#25355
=> Add the package Utilities/PSS to the simulation category

categories.py
As agreed with @santocch and @tommasoboccali, A. Santocchia is added as "analysis" category manager
=> Add Santocchia to analysis category

es_utils.py, getWorkflowStatsFromES.py
Imports es_query from es_utils to get the releases data.
Sets the histo titles and axis units
=> Update metrics comparison script to use new es queries

categories_map.py
This proposed addition follows cms-sw/cmssw#25637
=> Add LICENSE and NOTICE files to core

categories.py
Remove Luca Pernie from AlCa task
=> Remove Luca Pernie from AlCa task

categories.py
=> Remove myself from l1 sign

report-build-release-status.py
we will re-enable it for cvmfs once we have jenkins job for it
=> Disable installation on AFS message for release builds

jenkins/system-info.sh
Update system info script to always follow default cmsdist branch
=> Update system info

groups.yaml
Removing myself from the BTV watchers list
=> Update btv group

categories_map.py
=> Add TICL package under upgrade

run-pr-comparisons
Adding a tool that compares CMSSW DQM monitor elements bin by bin and uploads only changed files to development version of DQM GUI.
=> Adding DQM bin by bin comparison tool

comparisons/matrix_RE.txt, comparisons/validate.C
- plots for PPS protons
- updated map file to include JetHT workflows (used in local/private tests).
=> reco comparisons: plots for PPS protons

run-pr-tests
=> Revert "Add TimeMemorySummary.py as default option for every runTheMatrix.py workflow"

run-pr-tests
=> Revert "Revert "Add TimeMemorySummary.py as default option for every runTheMatrix.py workflow""

categories_map.py
cms-sw/cmssw#26347 introduces the new validation package Validation/MtdValidation, added in the DQM category.
=> Add new package Validation/MtdValidation in support of cmssw PR 26347

categories.py
=> Add Chris West as L2 AlCa

categories.py
Add Tapio Lampen @tlampen as AlCaDB convener
=> Add Tapio Lampen as AlCaDB convener

watchers.yaml
I would like to request to be added to the watchers' list for GEM related packages.
=> adding jshlee to gem watchers

pr_testing/test_multiple_prs.sh, run-pr-tests
Cleaned version of #1122 with protection for non existent customisation file (for old branches)
=> Addition of timing and memory check if available in PR matrix test

run-pr-comparisons
Added support to [recently introduced changes](https://github.com/cms-sw/cmssw/pull/26848) in the DQM bin by bin comparison tool.
=> Added support for changed DQM bbb comparison tool

watchers.yaml
@Martin-Grunewald liked to remove following 
- SLHCUpgradeSimulations
- FastSimulation
=> Martin-Grunewald requested this cleanup

create-new-data-pr.py
we are using old PyGithub API that doesn't have some functionality,
some things were different. Adjusted
=> Add modifications for the old pygithub api

run-pr-code-checks
@fabiocos , this should enable code-format for latest release cycles.
=> enable code-format for latest releases with new config_tag

categories.py
Upon request of @ssekmen in https://github.com/cms-sw/cmssw/pull/27425#issuecomment-510951331
=> Add account sbein as new fastsim review responsible

es_reindex_indexes_with_pattern.py
script used by reindex-elasticsearch-indexes for reindexing existing indexes (indices ?)
need to apply in case new template was pushed for that index (re-mapping of the indexes)
=> Add elasticsearch reindexing script to cms-bot

groups.yaml
I want to subscribe to btv-pog PRs. As far as i can understand this is the way to do so.
=> Subscribing to btv-pog PR updates

watchers.yaml
=> clelange watch HGCal-related packages

es_relval_log.py
=> Remove test index creation

watchers.yaml
=> Add module to Watchlist

categories.py
Give @chayanit the authorization to sign for the pdmv category
@prebello @zhenhu FYI
=> Add new pdmv convener to categories definition

categories_map.py
Add a new package RecoBTag/PixelCluster in support of cms-sw/cmssw#27738
=> Add RecoBTag/PixelCluster in support of cmssw PR 27738

categories.py
=> add Felice Pantaleo and Marco Rovere to PR test

categories.py
This will make my life slightly easier in my capacity as Deputy Release Manager.
=> allow kpedro88 to sign for operations

watchers.yaml
Could you please add me to the list of watchers? Thanks.
=> Addition to the list of watchers

categories_map.py
This package is added in https://github.com/cms-sw/cmssw/pull/27895
=> Add RecoTracker/MkFit package to reconstruction

pr_testing/test_multiple_prs.sh, report-pull-request-results.py
This will only run python3 tests for development release cycle i.e. for master banch only.
This should mark PR rejected if python3 compilation failed.
=> [Python3] run python3 tests for PRs

watchers.yaml
As the title suggests, this PR as packages to watch for me / @riga.
=> Add watch list for @riga

categories.py
Per direct request remove user @prebello as leaving the PdmV task
=> Update the categories list

watchers.yaml
...as the EGM reco L3 contact.
Cheers,
Afiq
=> afiqaize to watch EGM repo

ib-rotate-weeks
Variables initialized automatically using config.map instead of hardcoded values
=> Ib rotate weeks improved

watchers.yaml
added myself to `watchers.yaml` (would like to follow those pkgs for ongoing work on the HLT DQM)
=> updated watchers.yaml (user: missirol)

cmsdist_merge_permissions.py
@smuzaffar Shazad,
please found the PR to add new CMSWEB operator.
Best Regards, Lina.
=> updating CMSWEB users

categories_map.py
See https://github.com/cms-sw/cmssw/pull/28254
=> Add L1TGEM

comparisons/validate.C
Dropped all get prefixes from PPS/TOTEM leaves, following https://github.com/cms-sw/cmssw/pull/28252.
=> Update of PPS/TOTEM data formats accessors

comparisons/validate.C
- TICL multiclusters (development)
- add pat::Muon inverseBeta
- automate size detection for object vector/array scans; use instead of hard-coded ranges
=> update reco comparisons: new products, automate handling of range scans

watchers.yaml
Title says it all. @robervalwalsh is the new Strip local reconstruction and calibration convener.
=> Add robervalwalsh as watcher for Strips packages

watchers.yaml
As requested in https://github.com/cms-sw/cmssw/pull/28417#issuecomment-555106826
FYI @geoff-smith
=> Remove geoff-smith from watchers.yaml

process_pr.py
Same as #1233 but rebased over current cms-bot/master
=> Multi line comment changes rebased

categories_map.py
Final addition on top of #1064 to support cms-sw/cmssw#28537
=> Add new package Heterogeneous/CUDATest to the heterogeneous category

categories.py
Update of the L1 list according to new organigram for 2020.
@dpiparo @klute FYI
=> Add Silvio Donato as new release manager

categories_map.py
In support of cms-sw/cmssw#28612
=> Add DQMServices/Demo

comparisons/validate.C
- HFNose hits and layer clusters
- hgcalMultiClusters: pick a correct collection ncollection name, updated in 102X already
=> reco comparisons updates for HGCAL

common/get_config_map_line.sh, common/get_cpu_number.sh, pr_testing/_helper_functions.sh, pr_testing/get_source_flag_for_cmsbuild.sh, test-prs.sh
A helper scipt added to easily build and test cms PRs. This include cmdist, cms-externals and cms-data.
=> added helper scirpt to build and test cms prs

categories_map.py
The package is added in https://github.com/cms-sw/cmssw/pull/28792.
=> Add FWCore/SharedMemory to core

categories_map.py
new package is requested here https://github.com/cms-sw/cmssw/pull/28477
=> assign dqm for DPGAnalysis/HcalTools package

categories_map.py
Related to this https://github.com/cms-sw/cmssw/pull/28815
=> Add  RecoMTD/TimingIDTools under upgrade and reco

comparisons/validateJR.sh, jenkins-artifacts, logRootQA.py, run-pr-comparisons
- Run default and alternative comparison in parallel
- fixes for python3
- Allow to locally run it with dry run option (so that we do not upload results)
=> Improved PR comparison job

categories_map.py, watchers.yaml
In association with https://github.com/cms-sw/cmssw/pull/29141
=> add category and watcher for SONIC package

watchers.yaml
Add also SimCalorimetry to the list of packages I'd like to monitor as HGCAL DPG.
=> Add SimCalorimetry package

categories.py
Update of categories.py as asked by PPD.
Could you double check @srimanob ?
cc: @franzoni, @zhenhu, @wajidalikhan
=> Update of categories.py as asked by PPD

watchers.yaml
Define a list of packages I want to keep monitoring, regardless of my presence in other roles.
=> Add fabiocos to the watchers list

categories_map.py
New package introduced via https://github.com/cms-sw/cmssw/pull/29381
=> Added L1Trigger/TrackFindingTMTT under L1 categoriy

watchers.yaml
=> Add packages to watchlist

rucio/rucio.cfg
As requested here https://github.com/cms-sw/cmsdist/issues/5752
=> updated rucio config

watchers.yaml
Adding packages for  abdoulline
=> Adding a list of packge for abdoulline to watchers.yaml 

categories.py, gh-teams.py
Adding Gurpreet Singh Chahal: gurpreet.singh@cern.ch
=> adding new GEN L2

watchers.yaml
=> Add list of packages to watch by Sergio Lo Meo

categories.py
I propose to add mmusich in TRIGGER_PR_TESTS in order to trigger the PR tests
=> Add mmusich in TRIGGER_PR_TESTS

categories_map.py
in support of cms-sw/cmssw#29832
=> CommonTools/Egamma in reco (moved from RecoEgamma/EgammaTools)

rucio/setup.sh
This is causing issues for some people.
=> Remove color from ls in setup.sh

watchers.yaml
being one of the TRK POG conveners
=> added TRK POG related packeages to mtosi

watchers.yaml
Adding myself to the watcher list of tracking-related packages.
=> add JanFSchulte to watchers

categories_map.py, watchers.yaml
for https://github.com/cms-sw/cmssw/pull/30318
=> add SonicTriton package

categories.py
We can expect Joosep to start working on code review and signoff in the transition period already, before Sept.
=> add jpata to reco L2

categories.py
Adding the Loukas Gouskos and Mariarosaria D'Alfonso as new xpog manager.
=> Add gouskos and mariadalfonso as xpog

categories.py
Add Qiang Li as new release manager
https://indico.cern.ch/event/930017/contributions/3909384/attachments/2064111/3463582/CB129_Nominations.pdf
=> Add Qiang Li as new release manager

categories.py
After a bit more than two and a half years in Core DQM my last day at CERN has come. Over this time, we changed and improved many things in DQM, and I hope it is now in a better shape than ever and ready to handle the data taking for Run3. I am sure @jfernan2 and @andrius-k will take good care of it.
Thanks Everyone!
=> Categories: Remove myself from DQM L2s.

schedule-additional-tests
=> Use correct workflow 23434.21

categories.py, gh-teams.py, watchers.yaml
This PR is to update the GEN L2 list. Qiang is now operations only. I removed myself from watching as I am already included via L2.
=> added gurpreet, removed qiang, removed myself from watching

categories_map.py
From https://github.com/cms-sw/cmssw/pull/31455
=> Add  PhysicsTools/IsolationAlgos to reconstruction

groups.yaml, watchers.yaml
Added a new watchers group for pixel offline
@dkotlins @tvami
=> Added pixel-offline watchers group

categories.py
@YuanChao is a new AlCa software coordinator. We are adding him to the CMSSW L2 list for AlCa.
=> Add YuanChao to CMSSW L2 list for AlCa

categories_map.py
Package added in https://github.com/cms-sw/cmssw/pull/31703
=> Add CUDADataFormats/StdDictionaries for heterogeneous category

watchers.yaml
This is just to add myself as watcher for some CMSSW packages.
=> add myself as watcher

categories_map.py
see https://github.com/cms-sw/cmssw/pull/31629#issuecomment-710163243
@silviodonato , @jan-kaspar only in alca, right ?
=> Add CalibPPS/AlignmentRelative to alca

comparisons/matrix_RE.txt
added for wf 159.0, 311.0, and 312.0
the last one is needed in connection with cms-sw/cmssw#32025
=> reco comparisons: add maps for Run3/2021 HI MC workflows

watchers.yaml
Hi,
I'd like to update the list of packages that I watch, so I updated my list in the watchers.yml file.
Cheers!
=> Update watched packages for user riga.

watchers.yaml
Hi,
I'd like to add myself to the watchers of some L1T packages.
Cheers,
Dinyar
=> Watch L1T packages

groups.yaml, watchers.yaml
- Expanding the list of watched packages
- Adding Oz to the pixel-offline group
@tvami @OzAmram
=> Updates for pixel-offline

logRootQA.py
all updates are in logRootQA.py
- change the file selection to provide a list of changes in products for all available files
- also, cleanup debug printouts in functions
=> get product comparisons for all root files; clean up debugs in logRootQA.py

es_utils.py
change the index and doc names
=> Change ES index and doc name for externals stats

create-new-data-pr.py
To avoid creating more files for every new data repo
see also https://github.com/cms-sw/pkgtools/pull/170
=> Create master branch on data repo if it doesn't exist

pr_testing/_helper_functions.sh, pr_testing/run-pr-relvals.sh
Bug fix: Install GPU results for RelVals in its own directory
=> upload gpu results in its own dir

pr_testing/_helper_functions.sh, pr_testing/run-pr-relvals.sh, pr_testing/test_multiple_prs.sh
Additional relval test to run 
```
runTheMatrix.py -i all --maxSteps=2 --command '-n 1'
```
for all relvals with inputs.
Note, additional test is disabled for now
=> add relval input test

categories.py
This PR adds Francesco Brivio (@francescobrivio) and Helena Malbouisson (@malbouis) as alca L2s.
=> Add Francesco Brivio and Helena Malbouisson as alca L2s

es_utils.py
this gets the externals stats from elastic search for the last 30 days by default from externals_stats_summary_testindex*
=> Add functions to get externals stats

groups.yaml, watchers.yaml
Defines tau-pog group and adds watch list.
=> add tau-pog watchers

watchers.yaml
Remove me from watch list for Alignment and RecoTracker packages
=> Remove user from watch list

docker_launcher.sh
as reported here https://github.com/cms-sw/cmssw/issues/32918
=> unset SINGULARITY_BIND inside singularity

DMWM/install-wmcore.sh, DMWM/setup-rucio.sh, DMWM/test-wmcore.sh
This is a working in progress branch, I'm still testing things in jenkins.
=> Add setup-rucio.sh script to the DMWM jenkins setup

pr_testing/run-pr-profiling.sh, run-ib-igprof
Using options show on this page
https://igprof.org/analysis.html
=> Add sqlite file for MEM_LIVE report for IB and PR testing.

categories.py
@jmduarte @cecilecaillol @rekovic 
Could you confirm everything is correct?
=> Replace Javier with Cecile as l1t manager

categories.py
@Sam-Harper this gives you the possibility to trigger the PR tests
=> Add Sam Harper in TRIGGER_PR_TESTS

run_clang_static_analysis
Should go in  after https://github.com/cms-sw/cmssw/pull/33122
=> Static Analyzers script -- copy eventsetuprecord-get.yaml instead

pr_testing/test_multiple_prs.sh
Resolves https://github.com/makortel/framework/issues/69
=> Check static analyzer log for warning edm::eventsetup::EventSetupRecord::get called

categories_map.py
Added CalibPPS/TimingCalibration for AlCa
Follow-up for https://github.com/cms-sw/cmssw/pull/33215.
=> [PPS] Added CalibPPS/TimingCalibration

groups.yaml
=> remove smoortga from btv-pog groups.yaml

categories_map.py
Needed for https://github.com/cms-sw/cmssw/pull/33280
=> add DQM/TrackerRemapper to dqm signature area

process_pr.py
please see the https://github.com/cms-sw/cms-bot/issues/1539 issue
=> cms-bot: only allow valid characters for runTheMatrix opts

categories_map.py
added in https://github.com/cms-sw/cmssw/pull/33437
=> Add new package - IORawData/CSCCommissioning

categories.py
My term as AlCa L2 ended at the end of April so I will no longer be signing PRs for AlCa.
=> Update list of AlCa L2s

categories.py
=> added iarspider as externals L2

categories_map.py
Related to PR to cmssw https://github.com/cms-sw/cmssw/pull/33609
=> L1: add category for VertexFinder

categories_map.py
in connection with cms-sw/cmssw#32806
=> new package RecoTracker/DisplacedRegionalTracking in reconstruction

categories.py
franzoni no longer needs to be notified about CMSSW 
https://en.wikipedia.org/wiki/So_Long,_and_Thanks_for_All_the_Fish :)
=> remove franzoni from operations

DMWM/CompareTests.py, DMWM/activate-start-agent.sh, DMWM/deploy-wmagentpy3.sh, DMWM/install-wmcorepy3.sh, DMWM/latest-dmwm-versions.sh, DMWM/test-wmcorepy3.sh
Changes required for running WMCore Jenkins unit tests in a python3 stack, for the baseline tests.
=> WMCore scripts required for python3 tests

rucio/setup.sh
Fixes https://github.com/cms-sw/cmsdist/issues/6944
=> use full path /cvmfs/cms.cern.ch/common/cmsos

watchers.yaml
It is requested by Fabrizio Ferro.
=> Substitute PPS software person

categories.py
=> Allow Suvankar to trigger the PR test

groups.yaml
=> add mmusich as tracking-pog watcher

categories.py
This PR adds Tamas Almos Vami (@tvami) as AlCa L2.
=> Add Tamas Vami as alca L2

groups.yaml
Removing myself from the list of BTV POG package watchers
Keeping @emilbols and @andrzejnovak in the loop
=> Update of BTV POG package watchers

categories.py
Added @perrotta as release manager
=> Updated release manager list

categories.py
=> Add Adriano to upgrade categories

categories.py
=> Remove Silvio from CMSSW L1

categories.py
=> Remove Andrea from reconstruction

categories.py
Mostly as a backup next to Giacomo.
cc @ggovi @malbouis @francescobrivio
=> Adding AlCaDB conveners to the "db" signature

watchers.yaml
Added myself to watch Egamma repos for my position as an L3 convener for Egamma/reco
=> added wrtabb to watch Egamma related repos

categories.py
=> removing Chayanit as she stepped down from pdmv L2

watchers.yaml
=> updating watchlist of user:missirol

categories.py
Welcolme @missirol :-) 
https://indico.cern.ch/event/1071923/#4-presentation-spokesperson
=> Adding Marino Missiroli as HLT L2

watchers.yaml
=> Reduce watched packages for clelange

categories_map.py
to support the code added in cms-sw/cmssw#35836
=> add  RecoMuon/MuonRechitClusterProducer to the reco category

RelValArgs.py
See https://github.com/cms-sw/cmssw/issues/36256
=> Run wf 101 and 102 in single threaded mode

categories_map.py
for https://github.com/cms-sw/cmssw/pull/36273
=> Add Calibration/PPSAlCaRecoProducer to the alca category

categories_map.py
Needed for https://github.com/cms-sw/cmssw/pull/36214
=> Add CondTools/JetMET to db signature

watchers.yaml
I am leaving the CMS collaboration. @giovanni-mocellin taking over responsibilities for the GEM, CSC, and GEM-CSC triggers.
=> Remove dildick from watchers

categories.py
Adding Enrique Palencia Cortezon to level-1 trigger sign-off list, a new Level-1 Offline SW co-coordinator. Please merge. 
Attn @smuzaffar 
Thanks,
=> Add Enrique Palencia Cortezon to level-1 trigger sign-off list.

watchers.yaml
=> mmusich watches DQM/Si* and DQM/Track* packages

cmsdist_merge_permissions.py
@smuzaffar @amaltaro I propose to allow new CRAB DevOp @mapellidario (who will be with use next 3 years) to merge PR's on COMP branches. Hope it is OK with you. As you may now Daina will leave at end of year so having another person to cover for CRAB is good. No hurry to remove Daina, of course. BYW I thing Natalia Ratnikova is not active on CMS anymore.
=> adding DarioMapelli

watchers.yaml
=> remove notifications for cbernet

watchers.yaml
=> replacing Jan Kaspar (who is leaving CMS)

categories_map.py
needed for https://github.com/cms-sw/cmssw/pull/36276
=> Adding DQMOffline/MuonDPG to dqm signature

watchers.yaml
=> Added user:valsdav to watchers

categories_map.py
title says it all, needed for https://github.com/cms-sw/cmssw/pull/36546
=> add `RecoTracker/MkFitCMS` & `RecoTracker/MkFitCore` to reco review category

comparisons/matrix_RE.txt
to catch up with the updates added with cms-sw/cmssw#36942 in runTheMatrix.py
=> reco comparisons: add maps for Run3 data workflows

das-utils/das_client
Support dasgoclient extra options
=> support das extra options

categories_map.py
assign DataFormats/L1TMuonPhase2 to l1
=> assign DataFormats/L1TMuonPhase2 to l1

watchers.yaml
updated watchlist for `eyigitba`
=> updated watchlist for eyigitba

categories.py
This PR removes our former SW Engineer in DQM (Peerut) and replaces it with the new one (Michel Succar Medina).
=> Replace DQM SW Engineer

pr_testing/test_multiple_prs.sh
use `sort -n` to order the pr workflows
=> use sort -n for workflows sorting

categories.py
Remove jfernan2 from DQM. He is not convener anymore.
=> Remove jfernan2 from DQM

categories.py
=> Update PdmV list

pr_testing/gen-pr-install-cmssw.sh, pr_testing/test_multiple_prs.sh
this is copy of  https://cmssdt.cern.ch/jenkins/job/pr-publish-cmssw/ job and it uses https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_4_X/master/scram-project-build.file#L293-L304 logic to relocate cmssw externals symlinks
=> added gen-pr-install-cmssw.sh to install pr cmssw area on cvmfs

categories.py
Hi, Folks, 
PPD L1s have an agreement with @jfernan2, this was done by mistake (we probably miscommunicated to @emanueleusai, apologies!). Can he be added back? 
Thanks,
Jordan, Kaori, and Sal
=> Add Javi back please :)

categories.py
@smuzaffar 
do I also need to update the cmssw_l2/l2.json or is it automated?
=> move slava77 from reco L2 to tracking-pog, keep the PR test role

watchers.yaml
Remove cvuosalo (Carl Vuosalo) as a watcher. I no longer want to receive notifications of package changes.
=> Remove cvuosalo

categories.py
Fixes https://github.com/cms-sw/cmssw/issues/38654
=> remove lveldere as fastsim L2

categories_map.py
Replaced (unused) DataFormats/TotemDigi to DataFormats/TotemReco used in https://github.com/cms-sw/cmssw/pull/38886
=> Added DataFormats/TotemReco to reconstruction category

categories.py
Adding new GEN L2   
FYI:  @cms-sw/generators-l2
=> add the new GEN L2: Meng Lu

categories_map.py
Needed for https://github.com/cms-sw/cmssw/pull/38915
=> Add CondCore/PPSTimingCalibrationPlugins under db

categories_map.py
=> Revert "Add CondCore/PPSTimingCalibrationPlugins under db"

categories.py
=> Revert "add the new GEN L2: Meng Lu"

categories.py
=> Revert "Revert "add the new GEN L2: Meng Lu""

report-summary-merged-prs
This will enable Resource Piecharts and Reco Event loop links that have been missing since the update to the HLLHC workflow 39634.21.
=> Updated profiling result checked for to Run3 workflow 11834.21

categories_map.py
Adding a new package for HLT validation: Validation/HLTrigger
The corresponding PR to CMSSW is here: https://github.com/cms-sw/cmssw/pull/38593
Please let me know in case any additional information is required!
=> Adding Validation/HLTrigger

categories.py
FYI @mandrenguyen, starting September 2022, but we could add already now with all agreeing.
cc @cms-sw/reconstruction-l2
=> add Matt as the incoming reco convener

jenkins/parser/jenkins-parser-job.py, jenkins/parser/jenkins-retry-job.py
Follow-up PR of https://github.com/cms-sw/cms-bot/pull/1812
=> Apply path fixes and sanity checks to Jenkins parser job

categories.py
I am stepping off ORP.   Good luck @perrotta @rappoccio :)
=> remove qiang from CMSSW L1 and operation

process_pr.py, run-pr-code-checks
resolves https://github.com/cms-sw/cms-bot/issues/1820
bot should now allow `code-checks and apply patch` command
=> support auto applying code-checks patch

jenkins/parser/jenkins-parser-job.py, jenkins/parser/jenkins-retry-job.py, jenkins/parser/jobs-config.json
This PR contains:
1. Refactor of actions and notifications in different functions.
2. Add retry action after bringing the node off.
3. Update label of the parsed jobs when no action is taken.
4. Update job label based on the action taken by parser.
5. Add `gitErrors` category to `ib-run-pr-tests`, `build-any-ib`, `update-github-pages` and `ib-tag-and-schdule`.
=> [Jenkins parser job] Refactor parser, fix actions and add new errors

categories.py
good luck @mandrenguyen and @clacaputo! :)
=> Update categories.py for reco L2

groups.yaml
To receive notifications on new PRs related to BTV
=> Add AnnikaStein to btv-pog (new RECO contact)

groups.yaml
This group will allow to have common notifications for muon POG reco (offline) contacts
=> Create muon-reco group

categories.py
Adding @syuvivida to `dqm` signature as new DQM L2 convener.
FYI @cms-sw/dqm-l2
=> Add syuvivida as new DQM L2 convener

watchers.yaml
Update of pkg-watchlist of user `missirol`.
=> updated watchlist of user `missirol`

docker_launcher.sh
=> Mount /var/run/user and /run/user

watchers.yaml
To track the development and PRs
=> Added Prasant1993 to watch Egamma related repositories

categories_map.py
maybe not to be merged right away. there could be other packages falling in the MINIAOD category that xpog could be asked to review
=> add PAT packages to XPOG category

watchers.yaml
Please approve request to watcg egamma and hgcal related repositories
=> Adding sameasy to watch egamma and hgcal related repositories

jenkins/parser/actions.py, jenkins/parser/helpers.py, jenkins/parser/jenkins-parser-job.py, jenkins/parser/jenkins-parser-monitor-job.py, jenkins/parser/jenkins-retry-job.py
Cleanup will come in a separate PR.
=> [Parser] Write parser actions in json file and generate html page accordingly

watchers.yaml
added a-kapoor to watch E/Gamma related folders
=> added a-kapoor to watch E/Gamma related folders

jenkins/parser/actions.py, jenkins/parser/helpers.py, jenkins/parser/jenkins-parser-job.py, jenkins/parser/jobs-config.json
It includes a `create_gridnode` action and the error string "cannot open directory /cvmfs/.*cern.ch:" (it appears when trying to `ls` to a cvmfs repo and it is not mounted).
It also includes minor fixes and refactoring.
=> [Jenkins parser] Handle `/cvmfs` not mounted on grid nodes

jenkins/parser/jobs-config.json
It adds `ib-install-cvmfs` and `run-pr-code-checks` jobs to the parser, and new git error messages.
=> [Jenkins parser] Add new git error messages and jobs 

report-pull-request-results.py
This PR includes updates to the handling of the log files of the `addOnTests`, in order to cope with the changes in https://github.com/cms-sw/cmssw/pull/40018.
This PR is required by https://github.com/cms-sw/cmssw/pull/40018, and it shouldn't be merged if https://github.com/cms-sw/cmssw/pull/40018 won't be.
=> cope with improved logging of `addOnTests`

comparisons/validate.C, comparisons/validateJR.py
recent PR test in 5.3 failed.
this aim at fixing it by removing range based loops and enable from FWlite
=> Fix validate in 5.3

categories_map.py
as requested in https://github.com/cms-sw/cmssw/pull/40122
=> Add Geometry/HGCalTBCommonData under geometry

comparisons/validateJR.py
taking a stab at the last comment in #1886
=> switch between AutoLibraryLoader::enable() and FWLiteEnabler::enable()

categories_map.py
Needed by https://github.com/cms-sw/cmssw/pull/40207
=> add `CondCore/BasicCondPlugins` to `db` category signature

categories.py
Please consider this PR to add me as the new E/Gamma L2
=> Added E/Gamma L2

categories_map.py
Needed by https://github.com/cms-sw/cmssw/pull/40295
=> updated `categories_map.py` to include `SiStripMonitorApproximateCluster`

categories.py
Not DQM convener at present. Thank you!
=> Remove jfernan2

categories.py, categories_map.py, githublabels.py, process_pr.py
Resolves https://github.com/cms-sw/cms-bot/issues/1884
=> Added support for non-blocking dpg/pog labels based on changed packages

categories.py
=> Remove @ianna as geometry l2

process_pr.py
@missirol , this change should allow watchers to watch file level changes
=> cms-bot: allow to watch file level changes

pr_testing/run-pr-comparisons
Can be seen during PR tests in the 'checks' box at the bottom of the GitHub page.
=> fix typo "comparion"

categories_map.py
Added in https://github.com/cms-sw/cmssw/pull/40624
=> Add PerfTools/JeProf package under core signature

categories.py
=> Updating DQM/L2s list

categories_map.py
The PR https://github.com/cms-sw/cmssw/pull/40674 adds a new visualization package ```Fireworks/MTD```.
=> Add new package Fireworks/MTD to the Visualisation category

watchers.yaml
Adding some extra modules to watch on top of what's already in btv-pog (jets, nano, ml inference...)
Best regards,
Annika (BTV Reco)
=> Update watchers.yml (AnnikaStein)

categories_map.py
Title says it all, needed by https://github.com/cms-sw/cmssw/pull/40754
=> add CalibTracker/SiStripHitResolution package to alca category

watchers.yaml
Updated watchlist of user jlidrych (Jindrich Lidrych).
=> Updated watchlist of user jlidrych

categories.py
Added Andrew Loeliger and removed Vladimir Rekovic
=> update L1T members

categories.py
=> adding Simone Pigazzini as XPOG

github_utils.py, ib-create-tag.py, tag-and-schedule-ibs
=> Use github api to check for/create CMSSW tag

release-notes
=> Add non-blocking dpg/pog labels to release summary

categories.py, groups.yaml
=> New ECAL DPG convener: Jin Wang

categories_map.py
See discussion in https://github.com/cms-sw/cmssw/pull/41607
=> Add DPGAnalysis/HcalNanoAOD to XPOG

categories_map.py
Add DPGAnalysis/HcalNanoAOD to CMSSW_LABELS HCAL. No signature is needed.
=> Add DPGAnalysis/HcalNanoAOD to CMSSW_LABELS HCAL

pr_testing/retry-command.sh, run-ib-pr-matrix.sh
pr input relval tests sometime fails due to das or xrootd errors. This PR allows to try these tests multiple time
=> retry input tests multiple times

watchers.yaml
Removing myself from the watchers list since I am no longer working at CERN.
It has been a pleasure working here, enjoy ! :-)
=> Removing hdelanno from watchers.yaml

categories.py
Remove Cecile Caillol from L1 category
=> Update L1 category: remove Cecile

buildLogAnalyzer.py
* Fix broken CSS URL 
* Replace `<class>...</class>` with `<span class=...></span>`
=> Fix generated log files; remove trailing whitespaces

categories.py
overlap started in June
@mmusich 
@kskovpen
=> add Kirill to tracking-pog

categories.py
Title says it all, I'm adding:
- @perrotta  (even though for now this might be redunant 😄 )
- @consuegs
as incoming `alca`-`db` conveners.
=> Add new ALCADB L2s

jenkins/parser/actions.py, jenkins/parser/jenkins-parser-job.py, jenkins/parser/jenkins-parser-monitor-job.py
It fixes the known bugs from the parser job:
* Fix bug on builds with no name.
* Adds exception handling for missing build parameters.
* Recreates configuration files when missing.
Tested locally.
=> [PARSER] Improve exception handling and recreation of configuration files when missing

watchers.yaml
I haven't needed to comment on upgrade workflow/geometry PRs in a while.
=> remove kpedro88 as watcher of upgrade categories

categories_map.py
as requested https://github.com/cms-sw/cmssw/pull/40438#issuecomment-1657960217
=> Add PhysicsTools/Scouting under xpog

categories.py
Add Tamas to those who can sign for the analysis category (none so far...)
=> Update categories.py for the analysis category

parse_jenkins_builds.py
=> Adding "node offline" as reason for a job to be in the queue

groups.yaml
from software & algorithm subgroup
=> Add Ming-Yan to BTV group

categories.py
Add Antonio Vilela as release managers and L2 for opeartions
@antoniovilela @rappoccio
=> Update categories.py with Antonio as release manager

categories_map.py
=> Update categories_map.py with CondCore/BaseKeyedPlugins

categories.py
Remove AP from release management (sigh...)
=> Update categories.py for ORP

categories.py
=> Add Javier Fernandez as reco convener

categories.py
remove me as outgoing TRK POG convener.
=> remove outgoing TRK POG convener

categories_map.py
=> add  DQMOffline/RecoB to tracking (non-blocking) category

categories.py
as requested by @swagata87 [here](https://github.com/cms-sw/cms-bot/pull/2009#issuecomment-1725058081)
=> remove swagata87 as egamma-pog

categories_map.py
Add RecoParticleFlow/PFRecHitProducer package to categories_map.py. This is required for CMSSW PR cms-sw/cmssw#42807
=> Add RecoParticleFlow/PFRecHitProducer package

categories_map.py
Add CalibCalorimetry/EBPhase2TPGTools to Alca and L1
=> Add CalibCalorimetry/EBPhase2TPGTools

categories.py
I am not dqm-l2 anymore and current dqm-l2 will take over pr review starting October 1
=> Remove former dqm convenor

category-watchers.yaml
Adding @PonIlya as watcher of the `db` category.
Eventually we will move him to approver.
FYI @cms-sw/db-l2
=> Add PonIlya as db watcher

groups.yaml
Adding Reyer Band to watchers of ecal-offline group
=> Adding Reyer Band to ecal-offline group

watchers.yaml
So I can get notifications for changes to the muon geometry
=> Update watchers.yaml for watson-ij

check-future-commits-prs.py
add missing import and define `pr` variable
=> Fix check-future-commits-prs script

jenkins/system-info.sh
thsi should fix https://github.com/cms-sw/cmssw/issues/42992
=> disable killing of proofserv.exe processes

categories.py, categories_map.py
Added a new `l1scouting` category, introduced in the PR cms-sw/cmssw#43467. 
I'm not sure whether I can proceed with this PR or if I should wait for a formal request on the other PR.
Tagging @emeschi and @smorovic
=> Added l1scouting category

categories.py
Remove Simone, add Huilin.
@vlimant
=> XPOG officers update

categories.py
=> Add subir to upgrade L2

cms-docker-gh-issues.py
Used in https://cmssdt.cern.ch/jenkins/job/check-docker-container/
=> Use cms-docker issues to schedule and trigger builds for el8/el9 base image changes 

process_pr.py
- Clean up code
- Cache bot results for both issues and PR
- add more reactions `+1` or `-1` for special comments like `[un]assign cat`, `[un]hold`, `[+-]1` (signatures) etc.
- Cache reactions information to avoid github api calls
=> Added more reactions to special comments; cache the reactions to avoid api calls

process_pr.py
Just adding a whitespace to fix black complaining in PR testing
=> Fix black formatting in `process_pr.py`

github_utils.py, process-pull-request.py, process_pr.py
This is super fragile (it relies on exact signature of `Github.__init__`) and ugly (because Python **at runtime** automatically mangles names of class members that start with double underscore by prefixing them with actual class name)
=> Log requests

jenkins/parser/jobs-config.json
=> Update jobs-config.json: add "disk full" error with action nodeOff

groups.yaml
Adding new Reco contact @tsusa to the pixel-offline group
@mroguljic
=> Update for pixel-offline

watchers.yaml
Request to update the ```watchers.yaml``` for the user fabiocos.
=> Add user fabiocos as a watcher for RecoVertex

process_pr.py
=> Make `process_pr` reentrable

categories_map.py
needed for https://github.com/cms-sw/cmssw/pull/43941
=> added PhysicsTools/TensorFlowAOT under ml

process_pr.py
@smuzaffar following discussion in https://github.com/cms-sw/cmssw/pull/44025. This will cause us a few extra API calls, and will likely make squash detection less efficient, but at least the tests will run.
=> Fix handling of big cache

github_modified_files.py
looks like `pr.draft` change is not working
```
Traceback (most recent call last):
File "/build/cmsbld/jenkins/workspace/cms-prs-files/cms-bot/github_modified_files.py", line 94, in <module>
main()
File "/build/cmsbld/jenkins/workspace/cms-prs-files/cms-bot/github_modified_files.py", line 65, in main
if pr.state == "closed" or pr.draft:
AttributeError: 'PullRequest' object has no attribute 'draft'
```
=> Revert pr.draft change

category-watchers.yaml
Adding @JanChyczynski as watcher of the `db` category.
FYI @cms-sw/db-l2
=> Add JanChyczynski as db watcher

RelValArgs.py, checkLogFile.py, cms-docker-gh-issues.py, create-gh-issue.py, create-gh-pr.py, gh-teams.py, github_backup.py, github_utils.py, ib-pr-workflow-changed.py, new-release-cycle.py, process-build-release-request.py, process-error-reports.py, process_pr.py, report-build-release-status.py
I saw a typo in the cms-bot message here: https://github.com/cms-sw/cmssw/issues/44658#issuecomment-2050033640 
and checked for other typos in python file text output.
=> Fixed typos in bot printout messages 

categories_map.py
as requesteed here: https://github.com/cms-sw/cmssw/pull/44557
=> Register L1TMuonOverlapPhase2 into category map. 

report-summary-merged-prs.py
=> Use * instead of WORKFLOW so vtune log can be found

categories.py
=> Adding Felipe Silva for XPOG signature

categories_map.py
See https://github.com/cms-sw/cmsdist/issues/9202
FYI @cms-sw/reconstruction-l2
=> add RecoTracker/LSTCore under reco

categories_map.py
Needed by https://github.com/cms-sw/cmssw/pull/45085
=> Add `PhysicsTools/XGBoost` to ml category

lumi/connect.sh, lumi/get_slot.sh, lumi/jenkins_java.sh, lumi/update_image.sh
Node is launched with `.cms-bot/lumi/connect.sh $OS cms-bot/lumi/jenkins_java.sh` with `OS` value being `el8` or `el9`.
Script `update_image.sh` runs on the lumi user node and updates the `.sif` images given a target OS and architecture.
=> Connect Jenkins agent to LUMI slots

categories_map.py
Package added in https://github.com/cms-sw/cmssw/pull/44901
=> Add FWCore/TestModules to be signed by core

pr_testing/setup-pr-test-env.sh, run-ib-testbase.sh
https://github.com/apptainer/apptainer/pull/2220
=> Workaround for el9 host and apptainer instance issue

categories_map.py
This PR adds DQM/PFTasks package to DQM category. Needed for CMSSW-PR https://github.com/cms-sw/cmssw/pull/45079
=> Add DQM/PFTasks to dqm category

categories_map.py
in connection with https://github.com/cms-sw/cmssw/pull/45117
=> add package RecoTracker/LST to reconstruction

jobs/run.sh, pr_testing/setup-pr-test-env.sh, run-hlt-validation, run-ib-pr-matrix.sh, run-ib-testbase.sh, run-tests-release
Useful for LUMI nodes where SITECONF should come from `T2_FI_HIP`
=> Override local SITECONF if needed

pr_testing/test_multiple_prs.sh, run-ib-pr-matrix.sh
To test https://github.com/cms-sw/cmssw/pull/45150
=> revert maxmem_profile change

generate-categories-json.py
@smuzaffar let me know if I should've only changed hashbang and removed import
=> Improve generate-categories-json.py

jenkins-artifacts, logUpdater.py
=> Add lxplus tunneling if not CERN domain

lumi/connect.sh, lumi/get_slot.sh
Get kerberos credentials from Jenkins server.
Set CMS env vars instead of setting them in Jenkins.
=> Get kerberos credentials for LUMI from Jenkins

watchers.yaml
Request to update watchers.yaml for user martinamalberti
=> Added martinamalberti as watcher

pr_testing/test_multiple_prs.sh, run-pr-code-checks
I will add/modify Jenkins job once this PR is approved.
=> Move checking git repo size change to a separate test

process_pr.py
=> Limit how many files can be changed in a PR

categories.py
=> add Mario to tracking POG

watchers.yaml
Added myself to the GeneratorInterface/CepGenInterface watchers list
=> Update of watchers.yaml for @forthommel

categories.py
=> Adding YaoYao - new ML Prod L3

report-summary-merged-prs.py
@makortel @smuzaffar this is why the Resources Piecharts links are not being added to the IB dashboard.
=> Change default profiling workflow searched for

report-summary-merged-prs.py
=> vtune results : use command with WORKFLOW substituted.

report-summary-merged-prs.py
@smuzaffar one last tweak to the tune link.
=> vtune link: add missing /

categories_map.py
Needed by https://github.com/cms-sw/cmssw/pull/45842
=> add `RecoVertex/PixelVertexFinding` to reco L2 signature area

pr_testing/run-pr-comparisons
addresses https://github.com/cms-sw/framework-team/issues/673
=> Compare maxmem_profile.txt for each workflow with comparison release

ib-create-tag.py
`current_tz` function taken from https://stackoverflow.com/a/59673310
=> ib-create-tag: fix searching for last commit to include in IB

categories.py
sadly I am leaving the xpog category
=> remove vlimant form xpog category

categories.py
my POG position ended on Sep 1.
=> remove slava77 from tracking POG category

gh-teams.py
As discussed privately with @smuzaffar
=> Add remaining framework people to core-team

categories.py
Add Moanwar to upgrade category.
=> Add Moanwar to upgrade category

s3/s3-upload-policy.sh, s3/s3utils.sh
Hello. The --region parameter was updating the wrong, misspelled variable. Also some typos in the usage printout.
=> Region parameter was not respected - also usage typos

lumi/get_slot.sh
The changes have been tested in Jenkins manually.
=> LUMI new singcvmfs setup

categories_map.py
Add `EventFilter/Phase2PixelRawToDigi` to `categories_map.py`.  This is requested in [#45759](https://github.com/cms-sw/cmssw/pull/45759)
=> add `EventFilter/Phase2PixelRawToDigi` to `catagories_map.py`

categories.py
Removed @aandvalenzuela
Thanks @aandvalenzuela for all the hard work you have done
=> cleanup cms-sdt team

category-watchers.yaml
Remove silviodonato from HLT watchers
=> Remove silviodonato from HLT watchers

categories.py, groups.yaml
- Adds Henriette Petersen as TkDPG convener.
- Adds Richa Sharma in Tk-DQM group
- Removes Suvankar Roy Chowdhury as TkDPG convener
=> Add Henriette Petersen as Tracker DPG convener

categories_map.py
Package is added in https://github.com/cms-sw/cmssw/pull/47033
=> Add HeterogeneousCore/AlpakaMath package to heterogeneous

es_relval_log.py
Solves https://github.com/cms-sw/cms-bot/issues/2417
=> Send stacktrace to es

lumi/get_slot.sh, repo_config.py
Required for https://github.com/cms-sw/cms-bot/pull/2418
=> Allow overriding path to github-token via env variable

es_ibs_log.py
As requested in https://github.com/cms-sw/cms-bot/pull/2419#issuecomment-2609448212
The `:=` (walrus) operator was introduced in Python 3.8, and on cmssdt, Python version is 3.9.
=> Send stacktraces from unit tests to ES

pr_testing/test_multiple_prs.sh
ignore header consistency check for headers which are explicitly marked as deprecated using `#error `
=> fix header consistency check: ignore headers with #error

cuda/install-cuda.py
The script was failing with the following error:
```
09:40:39 Traceback (most recent call last):
09:40:39   File "/home/cvcms-restricted/cache/cms-bot/cuda/install-cuda.py", line 763, in <module>
09:40:39     main()
09:40:39   File "/home/cvcms-restricted/cache/cms-bot/cuda/install-cuda.py", line 742, in main
09:40:39     install_package(component, archive_dir, install_dir, rules)
09:40:39   File "/home/cvcms-restricted/cache/cms-bot/cuda/install-cuda.py", line 496, in install_package
09:40:39     movetree(archive_dir, install_dir)
09:40:39   File "/home/cvcms-restricted/cache/cms-bot/cuda/install-cuda.py", line 180, in movetree
09:40:39     movetree(srcname, dstname, overwrite)
09:40:39   File "/home/cvcms-restricted/cache/cms-bot/cuda/install-cuda.py", line 187, in movetree
09:40:39 …
```
=> Fix installation of CUDA to cvcms-restricted

categories_map.py
Package added in https://github.com/cms-sw/cmssw/pull/47402
=> Add `FWIO/RNTuple` package for `core`

gh-teams.py
=> Allow core-team to have write access to framework-team repo

comparisons/resources-diff.py, pr_testing/run-pr-profiling.sh
Addresses https://github.com/cms-sw/cms-bot/pull/2441#issuecomment-2700325829
=> resources-diff.py: Fix order of diff in legend. Fix order of pr and ib data in Job line

pr_testing/_helper_functions.sh, pr_testing/run-pr-relvals.sh, run-ib-pr-matrix.sh
As requested here: https://github.com/cms-sw/cmssw/pull/47377#issuecomment-2735977206
=> Pass "--gpu required" when running RelVals on GPU

.github/workflows/test-changes.yaml, .github/workflows/test-process-pr.yaml, tests/run_pr_tests.sh
See https://github.com/actions/runner-images/issues/11101
=> Update workflows to use ubuntu-latest

pr_testing/run-pr-comparisons
See https://github.com/cms-sw/cmssw/pull/47884
=> Adjust to changed location of inspectNanoFile.py

ib-create-tag.py
=> Add extra logging to try and debug ib-create-tag.py failing 

categories.py
Remove Sandra from the AlCaDB signatures because she's not AlCaDB L2 any more since Apr 17
=> Remove Sandra from the AlCaDB signatures

process_pr.py
As requested in https://github.com/cms-sw/cmssw/pull/48009#issuecomment-2855187505
=> Automatically run code checks for branches that track devel branch

categories_map.py
Needed by https://github.com/cms-sw/cmssw/pull/48091.
@elenavernazza FYI
=> add `HLTrigger/NGTScouting` to hlt signature area

groups.yaml
This PR is to update the muon reco contacts in the Muon POG group.
=> Update muon-reco in groups.yaml

process_pr.py
=> Allow running changed process_pr code

pr_testing/_helper_functions.sh
@smuzaffar kind of urgent, to let the tests here run: https://github.com/cms-sw/cmssw/pull/48566
=> Handle utf-8 in JSON returnted by github

watchers.yaml
Adding myself (@IzaakWN) to packages relevant for development in the HGCal Raw-data group, and adding the same packages to my co-convener Pedro (@pfs).
@pfs, can you confirm, please?
=> Add HGCal Raw-data L3 to watchers.yaml

pr_testing/_helper_functions.sh, pr_testing/run-pr-relvals.sh, pr_testing/test_multiple_prs.sh, run-ib-pr-matrix.sh
Replaces https://github.com/cms-sw/cms-bot/pull/2507
=> Detect and report invalid workflow lists

pullPileup.py
Added pullPileup.py which enumerates the all pileup containers known to msPileup. A set of files containing the lfns associated with each container. A space delimited text file is a generated which maps container names to each lfn list.
=> pileup mapping script added

categories.py, groups.yaml
=> Tracking POG-related updates

process_pr.py
Technical change to avoid test failures like in https://github.com/cms-sw/cms-bot/pull/2580
=> Sort package categories when building messageNewPR
